// Generated by scripts/build-requirements.py from the requirements specification. Do not edit by hand.
export default {
 "intro": "<p>Each business requirement names its drivers, the parameters that test it, and the functional and non-functional requirements that deliver it. Success criteria can be measured. Where no baseline exists yet, the criterion says who will set it.</p>",
 "groups": [
  {
   "id": "business",
   "title": "Business requirements",
   "intro": "",
   "items": [
    {
     "id": "BR-001",
     "anchor": "br-001",
     "title": "Entitlement is decided correctly, as policy states it",
     "priority": "Must",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "Every decision applies the statute and the policy rules in force for the period it covers, as policy states them.",
     "fields": [
      {
       "label": "Description",
       "html": "<p>Every decision applies the statute and the policy rules in force for the period it covers, as policy states them. No worker should have to adjust a result by hand to reach the entitlement policy sets.</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>A benefits system that calculates something other than the stated entitlement pays people wrongly, at scale. Policy states at least one entitlement the current system does not calculate. Today the gap is closed only when a worker notices it and adjusts the amount by hand <span class=\"cite\">OBLG-C1</span>. A specification copied from the <a class=\"g\" href=\"%BASE%/glossary#old-system\">legacy system</a> would carry that underpayment forward. The rules also have no single current date: the supplement rules alone carry 54 different effective dates <span class=\"cite\">OBLG-C3</span>. Being correct means applying the right version of each rule to each period.</p>"
      },
      {
       "label": "Success Criteria",
       "html": "<ul><li><a class=\"g\" href=\"%BASE%/glossary#shadow\">Shadow comparison</a> meets its exit criteria for every class of difference, across three monthly payment cycles in a row, on a group of clients whose cases are as complex as the real caseload. There are zero unresolved defects in the new system before any group of clients moves (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-095\">FR-095</a>).</li><li>Every rule a decision applies is named in its record by rule identifier and version, and every rule in the register carries a policy citation and effective date (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-090\">FR-090</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-091\">FR-091</a>).</li><li>The entitlements that need manual adjustment today are calculated by the rules with no manual step. Test cases in the rules test suite prove it.</li></ul>"
      },
      {
       "label": "Drivers",
       "html": "<p>DRV-01, DRV-09, DRV-10</p>"
      },
      {
       "label": "Parameters",
       "html": "<p><a class=\"rid\" href=\"%BASE%/parameters#n01\">N01</a>, <a class=\"rid\" href=\"%BASE%/parameters#n04\">N04</a>, <a class=\"rid\" href=\"%BASE%/parameters#n07\">N07</a></p>"
      },
      {
       "label": "Delivered by",
       "html": "<p><a class=\"rid\" href=\"%BASE%/requirements/functional#fr-005\">FR-005</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-007\">FR-007</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-010\">FR-010</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-033\">FR-033</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-090\">FR-090</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-091\">FR-091</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-095\">FR-095</a></p>"
      },
      {
       "label": "Stakeholder",
       "html": "<p>Assistant Deputy Minister, Policy and Program Design</p>"
      }
     ]
    },
    {
     "id": "BR-002",
     "anchor": "br-002",
     "title": "Every decision can be defended years after it is made",
     "priority": "Must",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "Any decision can be reproduced, explained and disclosed for as long as it can be reconsidered, appealed, reviewed or requested under access legislation.",
     "fields": [
      {
       "label": "Description",
       "html": "<p>Any decision can be reproduced, explained and disclosed for as long as it can be reconsidered, appealed, reviewed or requested under access legislation. That means what was decided, on what facts, under which rules, and what the client was told.</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>A tribunal asks what the ministry decided, on what basis, and what the client was told, and it often asks years later. A decision can only be reproduced if the calculation depends on nothing but its inputs, and if those inputs and outputs are stored in full when the decision is made <span class=\"cite\">TA-C3</span>. A record that points to a running system is not evidence.</p>"
      },
      {
       "label": "Success Criteria",
       "html": "<ul><li>For a randomly chosen adverse decision, the rule, the fact and where it came from, the reasons as issued, and the deadline to challenge that was stated can all be rebuilt from stored records alone, with no running system and no person involved (TA §C.8.5 test).</li><li>The <a class=\"g\" href=\"%BASE%/glossary#replay\">replay</a> horizon, and how decisions older than it will be evidenced, are set out in writing before the first live decision (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-008\">FR-008</a>).</li><li>The appeal record for any decision can be put together, and severed, on demand (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-058\">FR-058</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-078\">FR-078</a>).</li></ul>"
      },
      {
       "label": "Drivers",
       "html": "<p>DRV-02, DRV-03, DRV-11 (aim 1)</p>"
      },
      {
       "label": "Parameters",
       "html": "<p><a class=\"rid\" href=\"%BASE%/parameters#n07\">N07</a>, <a class=\"rid\" href=\"%BASE%/parameters#n08\">N08</a>, <a class=\"rid\" href=\"%BASE%/parameters#n09\">N09</a></p>"
      },
      {
       "label": "Delivered by",
       "html": "<p><a class=\"rid\" href=\"%BASE%/requirements/functional#fr-001\">FR-001</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-002\">FR-002</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-008\">FR-008</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-009\">FR-009</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-058\">FR-058</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-062\">FR-062</a></p>"
      },
      {
       "label": "Stakeholder",
       "html": "<p>Chief Architect, with the <a class=\"g\" href=\"%BASE%/glossary#rafu\">Reconsideration and Administrative Fairness Unit</a></p>"
      }
     ]
    },
    {
     "id": "BR-003",
     "anchor": "br-003",
     "title": "Clients can always challenge a decision, and are told truthfully how",
     "priority": "Must",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "A client may ask for reconsideration of any communication, at any time, and the request is always recorded.",
     "fields": [
      {
       "label": "Description",
       "html": "<p>A client may ask for reconsideration of any communication, at any time, and the request is always recorded. The client is told accurately whether a decision can be reconsidered or appealed, and where. Statutory deadlines are tracked by the system, and the ministry's own lateness never costs the client.</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>Policy gives an unconditional right to ask for reconsideration. An independent unit decides whether reconsideration is available; the worker who sent the communication does not <span class=\"cite\">OBLG-C4</span>. Whether a decision can be challenged differs by entitlement and by <a class=\"g\" href=\"%BASE%/glossary#variant\">variant</a>, and cannot be worked out from the parent program <span class=\"cite\">PRIN-C2</span>. A missed statutory deadline changes what the client is owed <span class=\"cite\">PRIN-C1</span>.</p>"
      },
      {
       "label": "Success Criteria",
       "html": "<ul><li>No reconsideration request is refused at the point of contact on any channel, and every one is recorded with the date and channel it arrived on (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-055\">FR-055</a>).</li><li>Every entitlement and variant records its <a class=\"g\" href=\"%BASE%/glossary#statutory-basis\">statutory basis</a>, whether it can be reconsidered, whether it can be appealed, and to which body. The rights text in every notice is generated from those values (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-092\">FR-092</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-063\">FR-063</a>).</li><li>Every breach of a statutory deadline is detected and recorded automatically, and its effect on entitlement is applied without anyone asking (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-061\">FR-061</a>).</li></ul>"
      },
      {
       "label": "Drivers",
       "html": "<p>DRV-02, DRV-09</p>"
      },
      {
       "label": "Parameters",
       "html": "<p><a class=\"rid\" href=\"%BASE%/parameters#n19\">N19</a>, <a class=\"rid\" href=\"%BASE%/parameters#n20\">N20</a>, <a class=\"rid\" href=\"%BASE%/parameters#n17\">N17</a></p>"
      },
      {
       "label": "Delivered by",
       "html": "<p><a class=\"rid\" href=\"%BASE%/requirements/functional#fr-006\">FR-006</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-055\">FR-055</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-056\">FR-056</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-057\">FR-057</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-061\">FR-061</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-063\">FR-063</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-092\">FR-092</a></p>"
      },
      {
       "label": "Stakeholder",
       "html": "<p><a class=\"g\" href=\"%BASE%/glossary#rafu\">Reconsideration and Administrative Fairness Unit</a></p>"
      }
     ]
    },
    {
     "id": "BR-004",
     "anchor": "br-004",
     "title": "Public money moves only under control, and people are paid even when the system fails",
     "priority": "Must",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "Every payment passes through one defined issuance point.",
     "fields": [
      {
       "label": "Description",
       "html": "<p>Every payment passes through one defined issuance point. <a class=\"g\" href=\"%BASE%/glossary#separation-of-duties\">Separation of duties</a> is enforced in the software. <a class=\"g\" href=\"%BASE%/glossary#issuance-run\">Payment runs</a> never pay twice and can resume after a failure. Payments are reconciled daily against the <a class=\"g\" href=\"%BASE%/glossary#cas\">corporate financial system</a> in a three-way check. A planned, rehearsed emergency payment route exists before the first payment.</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>A benefits system that calculates correctly but does not pay has failed completely. A single issuance point that is described but never specified cannot be built. If each program family builds its own link to the payment system, the controls exist once per program and are audited once per program <span class=\"cite\">TA-C4</span>. Rolling back to the old system does not keep payments flowing: a client's rent is due on a date <span class=\"cite\">TA-C5</span>.</p>"
      },
      {
       "label": "Success Criteria",
       "html": "<ul><li>The five acceptance criteria for the issuance point in TA §C.6.8 pass before the first live payment (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-042\">FR-042</a>).</li><li>No payment is made outside a run, and there are no unexplained reconciliation breaks at month-end (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-043\">FR-043</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-045\">FR-045</a>).</li><li>Emergency payment is exercised, at a load-tested share of a program's caseload, before <a class=\"g\" href=\"%BASE%/glossary#module\">M6</a> ends (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-047\">FR-047</a>).</li></ul>"
      },
      {
       "label": "Drivers",
       "html": "<p>DRV-07, DRV-10, DRV-11 (aims 13, 14)</p>"
      },
      {
       "label": "Parameters",
       "html": "<p><a class=\"rid\" href=\"%BASE%/parameters#n17\">N17</a>, <a class=\"rid\" href=\"%BASE%/parameters#n16\">N16</a> [PROPOSED]</p>"
      },
      {
       "label": "Delivered by",
       "html": "<p><a class=\"rid\" href=\"%BASE%/requirements/functional#fr-042\">FR-042</a> to <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-048\">FR-048</a></p>"
      },
      {
       "label": "Stakeholder",
       "html": "<p>Executive Financial Officer</p>"
      }
     ]
    },
    {
     "id": "BR-005",
     "anchor": "br-005",
     "title": "Debt is raised fairly, and can be reversed in bulk",
     "priority": "Must",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "An overpayment is calculated as the difference between two decision records.",
     "fields": [
      {
       "label": "Description",
       "html": "<p>An overpayment is calculated as the difference between two <a class=\"g\" href=\"%BASE%/glossary#decision-record\">decision records</a>. It is classified by what changed in the evidence, and raised only after a person decides it. Automatic raising is capped per cycle. Overpayments that share one cause are reviewed together as a group. A batch of overpayments can be reversed in one step, and any money already recovered is returned automatically.</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>Another jurisdiction ran a debt-raising program that was found unlawful. It raised debts automatically from averaged income data and made recipients prove they did not owe. The controls against that failure are cheap to build only before any debts exist <span class=\"cite\">TA-C6</span>. Whether a debt can be recovered depends on what the ministry knew and when, and only the evidence record captures that.</p>"
      },
      {
       "label": "Success Criteria",
       "html": "<ul><li>No overpayment is raised without a recorded <a class=\"g\" href=\"%BASE%/glossary#human-dm\">human decision-maker</a> for each component (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-052\">FR-052</a>).</li><li>Every overpayment component is classified from the type of evidence change and the party at fault that caused it (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-051\">FR-051</a>).</li><li>A raised batch can be reversed in one step, with recovery reversed and corrected notices issued. This is shown in testing before the first live decision (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-052\">FR-052</a>).</li></ul>"
      },
      {
       "label": "Drivers",
       "html": "<p>DRV-01, DRV-02, DRV-07</p>"
      },
      {
       "label": "Parameters",
       "html": "<p><a class=\"rid\" href=\"%BASE%/parameters#n01\">N01</a>, <a class=\"rid\" href=\"%BASE%/parameters#n06\">N06</a>, <a class=\"rid\" href=\"%BASE%/parameters#n17\">N17</a></p>"
      },
      {
       "label": "Delivered by",
       "html": "<p><a class=\"rid\" href=\"%BASE%/requirements/functional#fr-012\">FR-012</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-048\">FR-048</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-051\">FR-051</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-052\">FR-052</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-053\">FR-053</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-060\">FR-060</a></p>"
      },
      {
       "label": "Stakeholder",
       "html": "<p>Executive Financial Officer, with the Overpayment &amp; Recovery business owner</p>"
      }
     ]
    },
    {
     "id": "BR-006",
     "anchor": "br-006",
     "title": "Information is collected, used and disclosed lawfully by design",
     "priority": "Must",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "The system collects only what it needs.",
     "fields": [
      {
       "label": "Description",
       "html": "<p>The system collects only what it needs. It discloses only where a legal basis is recorded. It enforces limits on how information may be used, wherever the information goes. It severs records before release, handles correction requests across every place the information is held, and can answer \"whose information was accessed, by whom, and when\" with a query.</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>The original design had no part responsible for how the ministry manages the information it holds. About 15% of obligations had no part of the system to own them <span class=\"cite\">MAP-C1</span>, and every unowned intake obligation was about managing information <span class=\"cite\">NOTE3-C1</span>. Policy bars information the ministry holds lawfully from particular uses, in five different ways <span class=\"cite\">PRIN-C3</span>. Severing works phrase by phrase inside free-text notes <span class=\"cite\">OBLG-C5</span>.</p>"
      },
      {
       "label": "Success Criteria",
       "html": "<ul><li>Every disclosure record names the recipient, the legal basis and the agreement. No access decision is made from any source other than the <a class=\"g\" href=\"%BASE%/glossary#sharing-agreement\">agreement registry</a> (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-077\">FR-077</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-085\">FR-085</a>).</li><li>Every barred use is blocked by default at the point of use, and each blocked attempt is recorded as an event (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-080\">FR-080</a>).</li><li>The people affected by a privacy breach can be listed by a query (<a class=\"rid\" href=\"%BASE%/requirements/quality#nfr-c-001\">NFR-C-001</a>).</li></ul>"
      },
      {
       "label": "Drivers",
       "html": "<p>DRV-03, DRV-08</p>"
      },
      {
       "label": "Parameters",
       "html": "<p><a class=\"rid\" href=\"%BASE%/parameters#n06\">N06</a>, <a class=\"rid\" href=\"%BASE%/parameters#n13\">N13</a>, <a class=\"rid\" href=\"%BASE%/parameters#n21\">N21</a></p>"
      },
      {
       "label": "Delivered by",
       "html": "<p><a class=\"rid\" href=\"%BASE%/requirements/functional#fr-075\">FR-075</a> to <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-083\">FR-083</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-085\">FR-085</a></p>"
      },
      {
       "label": "Stakeholder",
       "html": "<p>Ministry Privacy Officer</p>"
      }
     ]
    },
    {
     "id": "BR-007",
     "anchor": "br-007",
     "title": "Records can be disposed of lawfully in a store that never overwrites",
     "priority": "Must",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "Before the first live event is written, the ministry decides for each kind of fact how long it is kept and how it is disposed of.",
     "fields": [
      {
       "label": "Description",
       "html": "<p>Before the first live event is written, the ministry decides for each kind of fact how long it is kept and how it is disposed of. That includes the disposal method, the published list of what survives disposal, who holds the encryption keys, and what happens when a <a class=\"g\" href=\"%BASE%/glossary#replay\">replay</a> reaches a disposed fact. The ministry can then meet its disposal duties without destroying its financial and control records.</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>A store that only ever adds records conflicts with a legal duty to destroy them. Settling that conflict after the first event means rebuilding the store. The authority for disposal comes from the <em>Information Management Act</em> and the <a class=\"g\" href=\"%BASE%/glossary#ima\">ARCS/ORCS</a> schedules, not from the <a class=\"g\" href=\"%BASE%/glossary#bcea-manual\">policy manual</a> <span class=\"cite\">OBLG-C2</span>.</p>"
      },
      {
       "label": "Success Criteria",
       "html": "<ul><li>Every kind of fact has a disposal method before the first live event (<a class=\"rid\" href=\"%BASE%/requirements/data#dr-004\">DR-004</a>).</li><li>After a test disposal, financial <a class=\"g\" href=\"%BASE%/glossary#control-totals\">control totals</a> still reconcile to the same values as before (<a class=\"rid\" href=\"%BASE%/requirements/quality#nfr-c-003\">NFR-C-003</a>).</li></ul>"
      },
      {
       "label": "Drivers",
       "html": "<p>DRV-04, DRV-03</p>"
      },
      {
       "label": "Parameters",
       "html": "<p><a class=\"rid\" href=\"%BASE%/parameters#n12\">N12</a>, <a class=\"rid\" href=\"%BASE%/parameters#n08\">N08</a></p>"
      },
      {
       "label": "Delivered by",
       "html": "<p><a class=\"rid\" href=\"%BASE%/requirements/data#dr-004\">DR-004</a>, <a class=\"rid\" href=\"%BASE%/requirements/quality#nfr-c-003\">NFR-C-003</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-072\">FR-072</a></p>"
      },
      {
       "label": "Stakeholder",
       "html": "<p>Ministry Records Officer</p>"
      }
     ]
    },
    {
     "id": "BR-008",
     "anchor": "br-008",
     "title": "Indigenous jurisdiction and custodianship are recorded accurately",
     "priority": "Must",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "The system records who is custodian of each fact for each person.",
     "fields": [
      {
       "label": "Description",
       "html": "<p>The system records who is <a class=\"g\" href=\"%BASE%/glossary#custodian\">custodian</a> of each fact for each person. It treats Indigenous governing bodies as their own class of participant outside the Crown, with their own legal bases. It supports transferring records to another sovereign government as a way of disposing of them. And it recognises designations made by another jurisdiction, while showing how current that recognition is.</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>The <em><a class=\"g\" href=\"%BASE%/glossary#dripa\">Declaration on the Rights of Indigenous Peoples Act</a></em> commits the Province to bringing its laws into line with the UN Declaration. A Nation's authority over its own data cannot be expressed as a retention rule or an access list. The participant class and the custodianship attribute have to be built in from the start, because they cannot be added once the registry and evidence types exist <span class=\"cite\">TA-C7</span>.</p>"
      },
      {
       "label": "Success Criteria",
       "html": "<ul><li>The system can read the custodian of every evidence type for every person, and every access <a class=\"g\" href=\"%BASE%/glossary#decision-trace\">decision traces</a> to the <a class=\"g\" href=\"%BASE%/glossary#sharing-agreement\">agreement registry</a> alone (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-084\">FR-084</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-085\">FR-085</a>).</li><li>A transfer package can be produced, and the receiving body can check it without using ministry systems (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-084\">FR-084</a>).</li></ul>"
      },
      {
       "label": "Drivers",
       "html": "<p>DRV-06</p>"
      },
      {
       "label": "Parameters",
       "html": "<p><a class=\"rid\" href=\"%BASE%/parameters#n13\">N13</a></p>"
      },
      {
       "label": "Delivered by",
       "html": "<p><a class=\"rid\" href=\"%BASE%/requirements/functional#fr-021\">FR-021</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-084\">FR-084</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-085\">FR-085</a>, <a class=\"rid\" href=\"%BASE%/requirements/data#dr-005\">DR-005</a>, <a class=\"rid\" href=\"%BASE%/requirements/integrations#int-012\">INT-012</a></p>"
      },
      {
       "label": "Stakeholder",
       "html": "<p>Ministry Indigenous relations function, with the Ministry Privacy Officer</p>"
      }
     ]
    },
    {
     "id": "BR-009",
     "anchor": "br-009",
     "title": "Everyone can reach the service, whatever their ability or channel",
     "priority": "Must",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "A person gets the same result whatever their disability and whichever channel they use, with the same legal effect and the same deadlines.",
     "fields": [
      {
       "label": "Description",
       "html": "<p>A person gets the same result whatever their disability and whichever channel they use, with the same legal effect and the same deadlines. No right, notice or deadline to challenge is available only online. Screens meet <a class=\"g\" href=\"%BASE%/glossary#accessibility-standard\">WCAG 2.2 AA</a> at first release, confirmed by testing with <a class=\"g\" href=\"%BASE%/glossary#assistive-technology\">assistive technology</a>.</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>The clients least able to use a portal make up a large share of this caseload <span class=\"cite\">TA-C8</span>. A system that is correct but unreachable fails without showing up in usage figures. The <a class=\"g\" href=\"%BASE%/glossary#duty-accommodate\">duty to accommodate</a> is set in law (OB-IN-29).</p>"
      },
      {
       "label": "Success Criteria",
       "html": "<ul><li>For each part of the system, outcomes are measured across channels and reported at every gate (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-086\">FR-086</a>).</li><li>Evidence of accessibility, including results of manual testing with assistive technology, exists for every new screen before its gate (<a class=\"rid\" href=\"%BASE%/requirements/quality#nfr-u-002\">NFR-U-002</a>).</li></ul>"
      },
      {
       "label": "Drivers",
       "html": "<p>DRV-05, DRV-10</p>"
      },
      {
       "label": "Parameters",
       "html": "<p><a class=\"rid\" href=\"%BASE%/parameters#n15\">N15</a></p>"
      },
      {
       "label": "Delivered by",
       "html": "<p><a class=\"rid\" href=\"%BASE%/requirements/functional#fr-065\">FR-065</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-066\">FR-066</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-083\">FR-083</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-086\">FR-086</a> to <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-088\">FR-088</a>, <a class=\"rid\" href=\"%BASE%/requirements/quality#nfr-u-002\">NFR-U-002</a></p>"
      },
      {
       "label": "Stakeholder",
       "html": "<p>Head of Service Delivery Operations, with the Chief Digital Officer</p>"
      }
     ]
    },
    {
     "id": "BR-010",
     "anchor": "br-010",
     "title": "Policy changes are fast, safe and dated",
     "priority": "Must",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "Policy staff can write, test and release a rule or rate change without a software release.",
     "fields": [
      {
       "label": "Description",
       "html": "<p>Policy staff can write, test and release a rule or rate change without a software release. Each change is versioned and takes effect on its own date, after review and legal sign-off. Older versions of each rule can still run, for replaying past decisions and for transition rules that run alongside current ones.</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>The rules change all the time, and every decision draws on rules from several different dates <span class=\"cite\">RULES-C2</span>. Taking rate changes off the software release schedule is the main financial case for the rules platform. That case rests on an untested assumption: that policy analysts can write rules on it <span class=\"cite\">TA-C9</span>.</p>"
      },
      {
       "label": "Success Criteria",
       "html": "<ul><li>Two policy analysts, without help, write, test and release one real rate change from start to finish in a test environment, with the time taken and any help needed recorded (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-090\">FR-090</a>).</li><li>Every rule carries a policy citation and effective date. No rule is released while its effective dates in policy still conflict (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-091\">FR-091</a>).</li></ul>"
      },
      {
       "label": "Drivers",
       "html": "<p>DRV-09, DRV-10</p>"
      },
      {
       "label": "Parameters",
       "html": "<p><a class=\"rid\" href=\"%BASE%/parameters#n01\">N01</a>, <a class=\"rid\" href=\"%BASE%/parameters#n04\">N04</a>, <a class=\"rid\" href=\"%BASE%/parameters#n07\">N07</a></p>"
      },
      {
       "label": "Delivered by",
       "html": "<p><a class=\"rid\" href=\"%BASE%/requirements/functional#fr-010\">FR-010</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-090\">FR-090</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-091\">FR-091</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-094\">FR-094</a></p>"
      },
      {
       "label": "Stakeholder",
       "html": "<p>Assistant Deputy Minister, Policy and Program Design</p>"
      }
     ]
    },
    {
     "id": "BR-011",
     "anchor": "br-011",
     "title": "The legacy systems are replaced step by step, reversibly, and completely",
     "priority": "Must",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "Work moves from the legacy systems to the new system one part and one group of clients at a time.",
     "fields": [
      {
       "label": "Description",
       "html": "<p>Work moves from the <a class=\"g\" href=\"%BASE%/glossary#old-system\">legacy systems</a> to the new system one part and one group of clients at a time. There is exactly one writer per <a class=\"g\" href=\"%BASE%/glossary#aggregate\">aggregate</a> at every moment, per context and per <a class=\"g\" href=\"%BASE%/glossary#client-group\">cohort</a> (<a class=\"rid\" href=\"%BASE%/parameters#n05\">N05</a>). A published statement says what moving back would lose. The published interface outlives the legacy system behind it. Each legacy capability is shut down as its replacement goes live.</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>The vendor supports the legacy platform past 2037, so no outside deadline forces the replacement to finish <span class=\"cite\">TA-C10</span>. The previous programme replaced about a third of the legacy systems and left the most important one running. Responsibility for records moves one part of the system at a time, never one field at a time <span class=\"cite\">TA-C11</span>.</p>"
      },
      {
       "label": "Success Criteria",
       "html": "<ul><li>Every part of the system that moves meets the definition of done in TA §E.10, including retiring the legacy function and closing its interfaces.</li><li>Moving back is rehearsed for every group of clients before they move, and the list of what would be lost is published and accepted (<a class=\"rid\" href=\"%BASE%/requirements/data#dr-015\">DR-015</a>).</li><li>Removing the legacy product changes nothing in any published interface (<a class=\"rid\" href=\"%BASE%/requirements/quality#nfr-i-001\">NFR-I-001</a>).</li></ul>"
      },
      {
       "label": "Drivers",
       "html": "<p>DRV-11 (aims 3, 6, 7, 11)</p>"
      },
      {
       "label": "Parameters",
       "html": "<p><a class=\"rid\" href=\"%BASE%/parameters#n05\">N05</a>, <a class=\"rid\" href=\"%BASE%/parameters#n10\">N10</a>, <a class=\"rid\" href=\"%BASE%/parameters#n14\">N14</a></p>"
      },
      {
       "label": "Delivered by",
       "html": "<p><a class=\"rid\" href=\"%BASE%/requirements/data#dr-010\">DR-010</a> to <a class=\"rid\" href=\"%BASE%/requirements/data#dr-016\">DR-016</a>, <a class=\"rid\" href=\"%BASE%/requirements/quality#nfr-i-001\">NFR-I-001</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-095\">FR-095</a>, <a class=\"rid\" href=\"%BASE%/requirements/integrations#int-023\">INT-023</a></p>"
      },
      {
       "label": "Stakeholder",
       "html": "<p>Chief Architect</p>"
      }
     ]
    },
    {
     "id": "BR-012",
     "anchor": "br-012",
     "title": "Workers can do their jobs at least as well as today, and safely",
     "priority": "Must",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "In each part of the system, the ten most common tasks take no longer, and need no more screens or switches between systems, than today.",
     "fields": [
      {
       "label": "Description",
       "html": "<p>In each part of the system, the ten most common tasks take no longer, and need no more screens or switches between systems, than today. Supervisors can see caseloads across programs. Client and staff safety concerns are recorded and acted on.</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>Problems for workers, not missing features, sank the child protection phases of the previous programme. A move to the new system that makes a common task slower is a defect <span class=\"cite\">TA-C12</span>. Staff safety is part of the nature of the work.</p>"
      },
      {
       "label": "Success Criteria",
       "html": "<ul><li>Baselines are captured before each part of the system is built. In acceptance testing with real workers on realistic data, task times are at or below the baseline (<a class=\"rid\" href=\"%BASE%/requirements/quality#nfr-u-001\">NFR-U-001</a>).</li><li>Safety concerns are recorded and routed, with restricted handling applied, on every channel (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-089\">FR-089</a>).</li></ul>"
      },
      {
       "label": "Drivers",
       "html": "<p>DRV-10</p>"
      },
      {
       "label": "Parameters",
       "html": "<p><a class=\"rid\" href=\"%BASE%/parameters#n15\">N15</a>, <a class=\"rid\" href=\"%BASE%/parameters#n17\">N17</a></p>"
      },
      {
       "label": "Delivered by",
       "html": "<p><a class=\"rid\" href=\"%BASE%/requirements/functional#fr-032\">FR-032</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-067\">FR-067</a> to <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-070\">FR-070</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-089\">FR-089</a>, <a class=\"rid\" href=\"%BASE%/requirements/quality#nfr-u-001\">NFR-U-001</a></p>"
      },
      {
       "label": "Stakeholder",
       "html": "<p>Head of Service Delivery Operations</p>"
      }
     ]
    },
    {
     "id": "BR-013",
     "anchor": "br-013",
     "title": "A system failure never harms a client",
     "priority": "Must",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "Every service has an availability target, a recovery time and a recovery point, set by what its failure would do to clients and proven in exercises.",
     "fields": [
      {
       "label": "Description",
       "html": "<p>Every service has an availability target, a recovery time and a recovery point, set by what its failure would do to clients and proven in exercises. Anything that affects an entitlement or a payment must lose no data at all. Every dependency has a stated way of working when it fails.</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>A lost <a class=\"g\" href=\"%BASE%/glossary#payment-instruction\">payment instruction</a> is a person without money <span class=\"cite\">TA-C13</span>. <a class=\"rid\" href=\"%BASE%/parameters#n16\">N16</a>, the parameter that covers this, is still [PROPOSED], because none of the 270 <a class=\"g\" href=\"%BASE%/glossary#obligation\">policy obligations</a> calls for it <span class=\"cite\">PRIN-C4</span>. Its authority lies outside the <a class=\"g\" href=\"%BASE%/glossary#bcea-manual\">policy manual</a>; its need is not in doubt.</p>"
      },
      {
       "label": "Success Criteria",
       "html": "<ul><li>The C.15.1 capacity table has every cell filled, with an owner for each figure, at <a class=\"g\" href=\"%BASE%/glossary#design-freeze\">design freeze</a> (<a class=\"rid\" href=\"%BASE%/requirements/quality#nfr-p-001\">NFR-P-001</a>).</li><li>Recovery targets are proven in exercises for every <a class=\"g\" href=\"%BASE%/glossary#tier1\">tier-1</a> component, and disaster recovery exercises run twice a year (<a class=\"rid\" href=\"%BASE%/requirements/quality#nfr-a-002\">NFR-A-002</a>, <a class=\"rid\" href=\"%BASE%/requirements/quality#nfr-a-006\">NFR-A-006</a>).</li></ul>"
      },
      {
       "label": "Drivers",
       "html": "<p>DRV-07, DRV-10, DRV-11 (aim 13)</p>"
      },
      {
       "label": "Parameters",
       "html": "<p><a class=\"rid\" href=\"%BASE%/parameters#n16\">N16</a> [PROPOSED]</p>"
      },
      {
       "label": "Delivered by",
       "html": "<p><a class=\"rid\" href=\"%BASE%/requirements/quality#nfr-a-001\">NFR-A-001</a> to <a class=\"rid\" href=\"%BASE%/requirements/quality#nfr-a-007\">NFR-A-007</a>, <a class=\"rid\" href=\"%BASE%/requirements/quality#nfr-a-009\">NFR-A-009</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-047\">FR-047</a></p>"
      },
      {
       "label": "Stakeholder",
       "html": "<p>Ministry Chief Information Officer, with the Head of Service Delivery Operations</p>"
      }
     ]
    },
    {
     "id": "BR-014",
     "anchor": "br-014",
     "title": "Each program family is specified from its own law and policy before it moves",
     "priority": "Must",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "For child care subsidy, employment services and child protection, the obligations are extracted from each program's own legislation and policy, by the same method used for the BCEA register, before that program's module is scoped.",
     "fields": [
      {
       "label": "Description",
       "html": "<p>For child care subsidy, employment services and child protection, the obligations are extracted from each program's own legislation and policy, by the same method used for the BCEA register, before that program's module is scoped.</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>The detailed requirements here rest on the BCEA <a class=\"g\" href=\"%BASE%/glossary#bcea-manual\">policy manual</a>. The architecture covers more than that. The first set of rules it plans to move is child care subsidy (<a class=\"g\" href=\"%BASE%/glossary#module\">M5</a>), and no obligation register exists yet for that program. Specifying a program from the platform down, without its own authority, is the mistake the method was built to prevent <span class=\"cite\">METH-C2</span>.</p>"
      },
      {
       "label": "Success Criteria",
       "html": "<ul><li>Each program family has an obligation register, a <a class=\"g\" href=\"%BASE%/glossary#rules-register\">rules register</a> and a register of which decisions can be challenged, all with policy citations, before its module starts.</li><li>Every platform-level requirement in this document is re-checked against each new family's obligations, and gaps are raised as amendments.</li></ul>"
      },
      {
       "label": "Drivers",
       "html": "<p>DRV-01, DRV-08, DRV-09</p>"
      },
      {
       "label": "Parameters",
       "html": "<p><a class=\"rid\" href=\"%BASE%/parameters#n18\">N18</a></p>"
      },
      {
       "label": "Delivered by",
       "html": "<p>later versions of this document; <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-090\">FR-090</a>, <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-092\">FR-092</a></p>"
      },
      {
       "label": "Stakeholder",
       "html": "<p>Chief Architect, with the <a class=\"g\" href=\"%BASE%/glossary#program-policy-authority\">program policy authority</a> for each family</p>"
      }
     ]
    }
   ]
  }
 ]
};
