// Generated by scripts/build-requirements.py from the requirements specification. Do not edit by hand.
export default {
 "terms": {
  "active-active": {
   "term": "Active-active",
   "short": "Running a service at two or more sites at once, so either can carry the load if the other fails.",
   "body": []
  },
  "adjudicability": {
   "term": "Adjudicability",
   "short": "Four facts recorded for each entitlement: whether it is granted under a statute, whether its decisions can be reconsidered, whether they can be appealed, and to whom.",
   "body": []
  },
  "adjudicating-authority": {
   "term": "Adjudicating authority",
   "short": "A body allowed to decide or review a class of decisions. It can be inside the ministry or outside it, such as Pacific Blue Cross or CLBC.",
   "body": []
  },
  "adverse": {
   "term": "Adverse decision",
   "short": "A decision that denies, reduces or ends assistance, or creates a debt.",
   "body": []
  },
  "aggregate": {
   "term": "Aggregate",
   "short": "A cluster of data the system treats as one unit for changes, with its own rules that must always hold. Each aggregate has exactly one writer at any moment, per cohort (N05). Examples: an evidence succession set, a payment instruction, a disbursement, a repayable issuance.",
   "body": []
  },
  "api": {
   "term": "API, REST, GraphQL",
   "short": "An API is how systems ask each other for data or actions; REST and GraphQL are two common styles.",
   "body": []
  },
  "asserted-negative": {
   "term": "Asserted negative",
   "short": "A question asked and answered \"no\". It counts as evidence, unlike a blank that was never asked.",
   "body": []
  },
  "assisted-digital": {
   "term": "Assisted digital",
   "short": "A worker or representative completing an online transaction for someone, with the helper's identity recorded.",
   "body": []
  },
  "bff": {
   "term": "Back end for front end",
   "short": "A small server behind each user interface that holds the sign-in tokens, so they never sit in the browser.",
   "body": []
  },
  "bcea-manual": {
   "term": "BCEA Policy and Procedure Manual",
   "short": "The ministry's published policy manual for employment and disability assistance. Under the source hierarchy it overrides procedures and job aids, and legislation overrides it.",
   "body": []
  },
  "bceid": {
   "term": "BCeID, BC Services Card, IDIR",
   "short": "Provincial sign-in credentials: BCeID for individuals and businesses, the BC Services Card for citizens with verified identity, and IDIR for government staff.",
   "body": []
  },
  "benefit-component": {
   "term": "Benefit component",
   "short": "One part of an assistance payment, such as support, shelter or a supplement. Each component can take effect on a different date.",
   "body": []
  },
  "break-glass": {
   "term": "Break-glass access",
   "short": "Emergency access to a restricted record outside normal rules, always logged and reviewed afterwards.",
   "body": []
  },
  "byte-identical": {
   "term": "Byte-identical",
   "short": "Exactly the same, down to every character, with nothing that differs.",
   "body": []
  },
  "calendar-basis": {
   "term": "Calendar basis",
   "short": "Which calendar a time limit counts in, such as business days, calendar months or the school year.",
   "body": []
  },
  "capture": {
   "term": "Capture, states S0–S3",
   "short": "Moving a part of the service to the new system for a cohort, through four states: old system in charge (S0), shadow (S1), captured with write-back (S2), new system in charge (S3).",
   "body": []
  },
  "cfcsa": {
   "term": "CFCSA",
   "short": "The Child, Family and Community Service Act, BC's child protection law. Section 96 lets child protection workers request information.",
   "body": []
  },
  "cihr": {
   "term": "Child in the Home of a Relative (CIHR)",
   "short": "A closed program supporting children living with relatives. It runs on rules frozen in 2010 alongside the current rules.",
   "body": []
  },
  "ci": {
   "term": "CI (continuous integration)",
   "short": "The automated pipeline that builds and tests every change before it can be released.",
   "body": []
  },
  "circuit-breaker": {
   "term": "Circuit breaker, bulkhead, timeout",
   "short": "Protections that stop one failing service from taking others down with it.",
   "body": []
  },
  "client-index": {
   "term": "Client index",
   "short": "A single index for finding people and spotting duplicate records, with uncertain matches sent to a person to decide.",
   "body": []
  },
  "case-context": {
   "term": "Case context",
   "short": "One of the five program-family domain contexts (employment assistance, persons with disabilities, child care subsidy, employment services, child protection) that together form the Case & Service Delivery family. They share protocols, not a case model; the family name is never an owner (NFR-I-008; ADR-001).",
   "body": []
  },
  "cohort-review": {
   "term": "Cohort review",
   "short": "Holding a large group of new debts that share one cause for review before any notices go out.",
   "body": []
  },
  "component-library": {
   "term": "Component library (tiered)",
   "short": "Shared, reusable interface building blocks, split into tiers so accessibility logic sits in the shared lower tiers.",
   "body": []
  },
  "not-retainable": {
   "term": "Considered but not retainable",
   "short": "Evidence that policy lets staff look at but not keep, such as tax information that must not be printed.",
   "body": []
  },
  "control-totals": {
   "term": "Control totals",
   "short": "Counts and sums struck before a run is approved and checked unchanged afterwards.",
   "body": []
  },
  "cas": {
   "term": "Corporate Accounting System (CAS)",
   "short": "The Province's financial system of record. All payments are posted and reconciled against it.",
   "body": []
  },
  "correlation-id": {
   "term": "Correlation identifier",
   "short": "An ID carried through every step of a request so its whole path can be traced afterwards.",
   "body": []
  },
  "federal-benefits": {
   "term": "CPP, OAS, GIS, EI, SIN",
   "short": "Federal programs and identifiers: Canada Pension Plan, Old Age Security, Guaranteed Income Supplement, Employment Insurance, and the Social Insurance Number.",
   "body": []
  },
  "date-conflict": {
   "term": "Date conflict (rule status)",
   "short": "A rule that the policy manual gives two different effective dates. It cannot be released until the ministry rules on which date is right.",
   "body": []
  },
  "deidentified": {
   "term": "De-identified, synthetic, differentially private data",
   "short": "Data changed so people cannot be identified: identifiers removed, made up to look realistic, or blurred with statistical noise.",
   "body": []
  },
  "decision-class": {
   "term": "Decision class (A, B, C)",
   "short": "How a rule output is treated: A is an administrative decision needing reasons, B needs a human decision-maker before it is issued, C is an intermediate calculation never shown as a decision.",
   "body": []
  },
  "decision-trace": {
   "term": "Decision trace",
   "short": "The step-by-step record of which rules fired and with what values, in a format the ministry owns.",
   "body": []
  },
  "deemed-receipt": {
   "term": "Deemed receipt",
   "short": "The date a notice is treated as received, set by rule. The client's time to challenge counts from it.",
   "body": []
  },
  "degraded-mode": {
   "term": "Degraded mode",
   "short": "A planned, reduced way of working when a dependency fails.",
   "body": []
  },
  "delegated-agency": {
   "term": "Delegated agency",
   "short": "An organisation, including Indigenous agencies, authorised to deliver child and family services on the ministry's behalf.",
   "body": []
  },
  "design-freeze": {
   "term": "Design freeze",
   "short": "The point after which the design is fixed and building starts. Several decisions must be made before it.",
   "body": []
  },
  "discretionary": {
   "term": "Discretionary determination",
   "short": "A decision a person makes using judgement, recorded with their identity, authority and reasons.",
   "body": []
  },
  "driver": {
   "term": "Driver (DRV-)",
   "short": "The reason a requirement exists: a law, the policy manual, the nature of the work, or an aim of the architecture.",
   "body": []
  },
  "duty-accommodate": {
   "term": "Duty to accommodate",
   "short": "The Human Rights Code duty to adjust service for a person's needs, such as disability or language, unless there is a clear and justifiable reason it cannot be met.",
   "body": []
  },
  "ea-acts": {
   "term": "EA Act and EAPWD Act",
   "short": "The Employment and Assistance Act and the Employment and Assistance for Persons with Disabilities Act, with their regulations. They set who qualifies for assistance and how much.",
   "body": []
  },
  "effective-date": {
   "term": "Effective date",
   "short": "The date a rule, rate or decision takes effect. It is often different from the date it was published or made.",
   "body": []
  },
  "emergency-issuance": {
   "term": "Emergency issuance",
   "short": "A designed way to pay people when the normal decision process is down, using the same controls and settled later.",
   "body": []
  },
  "clock-class": {
   "term": "Entitlement clock, service-standard clock",
   "short": "A breach of an entitlement clock changes what the client is owed; a breach of a service-standard clock does not.",
   "body": []
  },
  "error-attribution": {
   "term": "Error attribution",
   "short": "Who caused a recorded mistake: the client, the ministry, a third party, or unknown. It must be recorded with every correction.",
   "body": []
  },
  "succession-set": {
   "term": "Evidence succession set",
   "short": "The stream of versions of one logical fact about one subject: the aggregate of the event-sourced Evidence & Verification context. Record, Correct, Supersede, Verify and Invalidate commands append to it; current state is a projection (DR-020).",
   "body": []
  },
  "evidence-programme": {
   "term": "Evidence programme",
   "short": "The first 90 days of the programme, used to test assumptions and settle early decisions. \"Day 45\" and \"Day 90\" count from its start.",
   "body": []
  },
  "evidence-tier": {
   "term": "Evidence tier (E1–E4)",
   "short": "Levels of proof kept about cross-organisation exchanges, from basic attributable logs (E1) to signed messages (E4).",
   "body": []
  },
  "excision-test": {
   "term": "Excision test",
   "short": "Removing the product behind an interface and counting how many interface changes that forces. The target is zero.",
   "body": []
  },
  "fmep": {
   "term": "FMEP",
   "short": "The Family Maintenance Enforcement Program, which collects court-ordered support. The ministry must disclose some debtor information to it on request.",
   "body": []
  },
  "hash-chain": {
   "term": "Hash, digest, hash chain",
   "short": "A digest is a short fingerprint of data that changes if the data changes; a hash chain links records by fingerprint so any tampering shows.",
   "body": []
  },
  "headroom": {
   "term": "Headroom factor",
   "short": "Extra capacity planned above the measured peak.",
   "body": []
  },
  "human-dm": {
   "term": "Human decision-maker",
   "short": "A named person with authority who decides, as opposed to the system computing a result. Some decisions must have one by law or policy.",
   "body": []
  },
  "idempotent": {
   "term": "Idempotent",
   "short": "Safe to repeat: doing it twice has the same effect as doing it once. Payment submission must be idempotent.",
   "body": []
  },
  "identity-assurance": {
   "term": "Identity assurance level",
   "short": "How confident the system can be that a person is who they say they are. Level 3 means identity was verified in person or equivalent.",
   "body": []
  },
  "ima": {
   "term": "Information Management Act, ARCS and ORCS",
   "short": "The law and the approved schedules (administrative and operational records classification systems) that say how long government records are kept and how they are destroyed.",
   "body": []
  },
  "invalidation": {
   "term": "Invalidation, rescission",
   "short": "Invalidation marks an evidence assertion that should never have existed. A tribunal rescission is different: the panel's rescinded determination is recorded as evidence, the original determination stands, annotated with the rescission, and the ministry makes a new retroactive determination (ADR-004). (v1.3 read \"Invalidation cancels a decision without replacing it, as when the tribunal rescinds one\".)",
   "body": []
  },
  "issuance-run": {
   "term": "Issuance run",
   "short": "A scheduled batch of payments with a cutoff, an approval and control totals.",
   "body": []
  },
  "issuance-service": {
   "term": "Issuance Service (payment chokepoint)",
   "short": "The single service every payment must pass through. No other part of the system can send money.",
   "body": []
  },
  "judicial-review": {
   "term": "Judicial review",
   "short": "A court's review of a tribunal decision, the last step after an appeal.",
   "body": []
  },
  "lakehouse": {
   "term": "Lakehouse, analytics platform",
   "short": "One governed store for analysis and reporting, so consumers query data without making new copies.",
   "body": []
  },
  "migration-event": {
   "term": "Migration event",
   "short": "A recorded event saying a record was imported from the old system, rather than inventing events that never happened.",
   "body": []
  },
  "modern-treaty": {
   "term": "Modern Treaty land",
   "short": "Land held by a First Nation under a modern treaty, where the Nation may run its own assistance program.",
   "body": []
  },
  "module": {
   "term": "Module (M0–M9)",
   "short": "A stage of delivery in the architecture. Each module is meant to be in use before the next is funded; M0 builds foundations and replaces nothing.",
   "body": []
  },
  "moscow": {
   "term": "MoSCoW priority",
   "short": "MUST_HAVE, SHOULD_HAVE, COULD_HAVE and WONT_HAVE: how essential a requirement is.",
   "body": []
  },
  "non-crown": {
   "term": "Non-Crown participant",
   "short": "A party that is not the provincial government, such as an Indigenous governing body acting under its own jurisdiction. Its legal authority is described in its own terms, not as a provincial law section.",
   "body": []
  },
  "obligation": {
   "term": "Obligation (OB-)",
   "short": "Something the policy manual requires the ministry to do or not do. The 270 obligations are numbered OB-xx-nn and each is traced to a requirement.",
   "body": []
  },
  "ocap": {
   "term": "OCAP",
   "short": "First Nations principles of ownership, control, access and possession of their own data.",
   "body": []
  },
  "oidc": {
   "term": "OIDC, token exchange",
   "short": "OpenID Connect is the standard sign-in protocol. Token exchange (RFC 8693) passes a user's authority to another organisation; rich authorization requests (RFC 9396) carry the legal basis with it.",
   "body": []
  },
  "overpayment": {
   "term": "Overpayment, administrative error",
   "short": "An overpayment is money paid that was not owed. When the ministry caused it (administrative error), different recovery rules apply.",
   "body": []
  },
  "p95": {
   "term": "p95, p99",
   "short": "The response time that 95% or 99% of requests are faster than.",
   "body": []
  },
  "pbc-clbc": {
   "term": "Pacific Blue Cross, CLBC, BCANDS",
   "short": "Outside bodies that make some decisions for the ministry: Pacific Blue Cross (dental, optical and hearing supplements), Community Living BC (travel supplement) and the BC Aboriginal Network on Disability Society (on-reserve disability designations).",
   "body": []
  },
  "partition": {
   "term": "Partition, partition predicate",
   "short": "Splitting a large table into parts (for example by date) so a query reads only the part it needs.",
   "body": []
  },
  "payment-instruction": {
   "term": "Payment instruction",
   "short": "The record of one payment to be made, linked to the decision it pays. It is never edited, only cancelled and replaced.",
   "body": []
  },
  "pci": {
   "term": "PCI-DSS",
   "short": "The card industry's security standard. Keeping card data out of ministry systems keeps them outside its scope.",
   "body": []
  },
  "pcms": {
   "term": "PCMS",
   "short": "The Provincial Contract Management System (on Salesforce), which manages service-provider contracts. It is a recent system, likely kept.",
   "body": []
  },
  "policy-as-code": {
   "term": "Policy-as-code",
   "short": "Access rules written as versioned, testable code instead of settings changed by hand.",
   "body": []
  },
  "pre-decision": {
   "term": "Pre-decision communication",
   "short": "A message giving reasons and a response deadline, stating that no decision has been made yet. An aggregate of Eligibility & Entitlement, outside the pure function, carrying a no_decision_made marker (FR-006; ADR-004).",
   "body": []
  },
  "prescribed-class": {
   "term": "Prescribed class",
   "short": "A group of people the regulations treat as meeting disability designation without the usual application, often because another body has already assessed them.",
   "body": []
  },
  "program-policy-authority": {
   "term": "Program policy authority",
   "short": "The ministry role responsible for a program's policy. It approves how rule outputs are classified and accepts what a rollback would lose.",
   "body": []
  },
  "protected-abc": {
   "term": "Protected A, B, C",
   "short": "Canadian government security classifications for sensitive information, with C the most sensitive. Protected C may only be stored on-premise.",
   "body": []
  },
  "pure": {
   "term": "Pure evaluation",
   "short": "A calculation that uses only the inputs it is given, with no clock, database or network calls, so it gives the same answer every time.",
   "body": []
  },
  "pwd": {
   "term": "PWD and PPMB",
   "short": "Persons with Disabilities designation and Persons with Persistent Multiple Barriers designation. Each gives access to higher rates or different rules.",
   "body": []
  },
  "rdsp": {
   "term": "RDSP, structured settlement",
   "short": "A Registered Disability Savings Plan; a structured settlement pays compensation in instalments. Both have special treatment in asset rules.",
   "body": []
  },
  "rafu": {
   "term": "Reconsideration and Administrative Fairness Unit",
   "short": "The independent ministry unit that makes reconsideration decisions and decides whether reconsideration is available.",
   "body": []
  },
  "regression-corpus": {
   "term": "Regression corpus",
   "short": "A set of test cases with known answers that every rules change must still pass.",
   "body": []
  },
  "release-train": {
   "term": "Release train",
   "short": "A fixed schedule of software releases that changes must wait for.",
   "body": []
  },
  "repayable": {
   "term": "Repayable issuance",
   "short": "Money paid now against a signed promise to repay, which becomes a debt only if a later decision goes against the client. An aggregate of Financial Components, which decides nothing; interim assistance pending reconsideration or appeal is its principal instance (FR-041; ADR-005).",
   "body": []
  },
  "replay-horizon": {
   "term": "Replay horizon",
   "short": "How long past decisions can be re-run, and what serves as the record after that.",
   "body": []
  },
  "rules-register": {
   "term": "Rules register",
   "short": "The list of every policy rule with its source page, effective dates and status, held apart from the requirements so that dollar amounts and day counts live in one place.",
   "body": []
  },
  "sbom": {
   "term": "SBOM, penetration test",
   "short": "A software bill of materials lists every component in a system; a penetration test is an authorised attack to find weaknesses.",
   "body": []
  },
  "secure-data-exchange": {
   "term": "Secure Data Exchange",
   "short": "The Province's gateway for sharing personal information between ministries. All cross-ministry traffic goes through it.",
   "body": []
  },
  "set-off": {
   "term": "Set-off",
   "short": "Recovering a debt by deducting it from another amount the ministry owes the same person.",
   "body": []
  },
  "shadow": {
   "term": "Shadow comparison",
   "short": "Running the new system's calculation on the same inputs as the old one and classifying every difference before switching over.",
   "body": []
  },
  "shadow-root": {
   "term": "Shadow root, shadow DOM",
   "short": "A browser feature that hides a component's inner structure. It can break links assistive technology relies on.",
   "body": []
  },
  "shred-survivor": {
   "term": "Shred-survivor set",
   "short": "The fixed list of facts that stay readable after a person's records are destroyed, such as payment totals and disclosure records.",
   "body": []
  },
  "slo": {
   "term": "SLO, SLA, error budget",
   "short": "A service level objective or agreement is a stated performance target; the error budget is how much failure the target allows.",
   "body": []
  },
  "sop": {
   "term": "SOP (standard operating procedure)",
   "short": "A ministry procedure telling staff how to do a task. SOPs are evidence of current practice, not the authority for a requirement.",
   "body": []
  },
  "source-hierarchy": {
   "term": "Source hierarchy (Tier 1, 2, 3)",
   "short": "The ranking of sources used to decide what the system must do: Tier 1 is legislation, Tier 2 is the policy manual, Tier 3 is practice (procedures, job aids, spreadsheets). A higher tier wins any conflict.",
   "body": []
  },
  "statutory-decision": {
   "term": "Statutory administrative decision",
   "short": "A decision made under a law about a person's rights or benefits. It carries a duty to give reasons and a right to challenge.",
   "body": []
  },
  "statutory-basis": {
   "term": "Statutory basis",
   "short": "The section of a law or regulation that grants an entitlement.",
   "body": []
  },
  "statutory-dm": {
   "term": "Statutory decision-maker",
   "short": "The person the law gives authority to make a program's decisions. Only they can approve a class of decisions to be issued without human review.",
   "body": []
  },
  "ledger": {
   "term": "Subsidiary ledger",
   "short": "The ministry's own record of what it owes, pays and recovers, reconciled to the corporate financial system.",
   "body": []
  },
  "sync": {
   "term": "Synchronous, asynchronous",
   "short": "Synchronous means the user waits for the answer; asynchronous means the work is queued and the answer comes later.",
   "body": []
  },
  "target-architecture": {
   "term": "Target architecture",
   "short": "The architecture document (version 2) describing the system that replaces ICM and MIS.",
   "body": []
  },
  "telemetry": {
   "term": "Telemetry, observability, OpenTelemetry",
   "short": "Data a system emits about its own behaviour (logs, metrics, traces) so problems can be found; OpenTelemetry is the open standard for it.",
   "body": []
  },
  "temporally-unverified": {
   "term": "TEMPORALLY_UNVERIFIED, INDETERMINATE",
   "short": "TEMPORALLY_UNVERIFIED marks a determination answering a valid-time question from migrated facts whose old-system dates are unknown: it can show an amount but not what the ministry knew at the time. INDETERMINATE is what a knowledge-state question (what did the ministry know, and when?) returns on such a fact; it never substitutes the import date (DR-013; ADR-002).",
   "body": []
  },
  "threat-model": {
   "term": "Threat model, runbook",
   "short": "A threat model lists how a part of the system could be attacked; a runbook is a written step-by-step procedure for operations staff.",
   "body": []
  },
  "three-dates": {
   "term": "Three dates (tri-temporal)",
   "short": "Each fact records when it was true, when this system learned it, and, for migrated facts, when the old system recorded it.",
   "body": []
  },
  "three-way": {
   "term": "Three-way reconciliation",
   "short": "Daily checking that the ministry's ledger, the bank's settlement files and the corporate financial system agree.",
   "body": []
  },
  "tier1": {
   "term": "Tier-1 component",
   "short": "A service whose failure stops payments or decisions, covered by 24-hour on-call.",
   "body": []
  },
  "mtls": {
   "term": "TLS, mutual TLS, SFTP",
   "short": "Encryption for data in transit. Mutual TLS has both sides prove who they are; SFTP is secure file transfer.",
   "body": []
  },
  "tombstone": {
   "term": "Tombstone",
   "short": "A marker left in place of destroyed data, so replay knows something was there and was lawfully destroyed.",
   "body": []
  },
  "true-up": {
   "term": "True-up",
   "short": "Working out, once the real decision is made, the difference between what an emergency payment paid and what was owed.",
   "body": []
  },
  "work-item": {
   "term": "Work item",
   "short": "A task assigned to a person or team, with a due date, priority and history.",
   "body": []
  },
  "write-back": {
   "term": "Write-back",
   "short": "Copying changes from the new system back into the old one so its reports and interfaces keep working during the move.",
   "body": []
  }
 },
 "usage": {
  "old-system": [
   {
    "id": "BR-001",
    "page": "business"
   },
   {
    "id": "BR-011",
    "page": "business"
   },
   {
    "id": "FR-095",
    "page": "functional"
   },
   {
    "id": "FR-098",
    "page": "functional"
   },
   {
    "id": "NFR-P-001",
    "page": "quality"
   },
   {
    "id": "NFR-S-001",
    "page": "quality"
   },
   {
    "id": "INT-013",
    "page": "integrations"
   },
   {
    "id": "INT-023",
    "page": "integrations"
   }
  ],
  "shadow": [
   {
    "id": "BR-001",
    "page": "business"
   },
   {
    "id": "INT-023",
    "page": "integrations"
   },
   {
    "id": "DR-003",
    "page": "data"
   },
   {
    "id": "DR-014",
    "page": "data"
   }
  ],
  "rafu": [
   {
    "id": "BR-002",
    "page": "business"
   },
   {
    "id": "BR-003",
    "page": "business"
   },
   {
    "id": "FR-056",
    "page": "functional"
   },
   {
    "id": "INT-011",
    "page": "integrations"
   }
  ],
  "replay": [
   {
    "id": "BR-002",
    "page": "business"
   },
   {
    "id": "BR-007",
    "page": "business"
   },
   {
    "id": "FR-008",
    "page": "functional"
   },
   {
    "id": "FR-011",
    "page": "functional"
   },
   {
    "id": "FR-058",
    "page": "functional"
   },
   {
    "id": "FR-065",
    "page": "functional"
   },
   {
    "id": "FR-091",
    "page": "functional"
   },
   {
    "id": "NFR-P-003",
    "page": "quality"
   },
   {
    "id": "NFR-A-006",
    "page": "quality"
   },
   {
    "id": "NFR-C-003",
    "page": "quality"
   },
   {
    "id": "NFR-I-003",
    "page": "quality"
   },
   {
    "id": "DR-004",
    "page": "data"
   },
   {
    "id": "DR-013",
    "page": "data"
   }
  ],
  "statutory-basis": [
   {
    "id": "BR-003",
    "page": "business"
   },
   {
    "id": "FR-092",
    "page": "functional"
   },
   {
    "id": "FR-099",
    "page": "functional"
   }
  ],
  "variant": [
   {
    "id": "BR-003",
    "page": "business"
   },
   {
    "id": "FR-033",
    "page": "functional"
   },
   {
    "id": "FR-092",
    "page": "functional"
   }
  ],
  "cas": [
   {
    "id": "BR-004",
    "page": "business"
   },
   {
    "id": "FR-042",
    "page": "functional"
   },
   {
    "id": "NFR-A-005",
    "page": "quality"
   },
   {
    "id": "NFR-S-003",
    "page": "quality"
   },
   {
    "id": "NFR-C-008",
    "page": "quality"
   },
   {
    "id": "INT-001",
    "page": "integrations"
   }
  ],
  "issuance-run": [
   {
    "id": "BR-004",
    "page": "business"
   },
   {
    "id": "FR-009",
    "page": "functional"
   },
   {
    "id": "NFR-P-002",
    "page": "quality"
   }
  ],
  "module": [
   {
    "id": "BR-004",
    "page": "business"
   },
   {
    "id": "BR-014",
    "page": "business"
   },
   {
    "id": "NFR-A-005",
    "page": "quality"
   },
   {
    "id": "INT-013",
    "page": "integrations"
   }
  ],
  "separation-of-duties": [
   {
    "id": "BR-004",
    "page": "business"
   },
   {
    "id": "FR-047",
    "page": "functional"
   }
  ],
  "decision-record": [
   {
    "id": "BR-005",
    "page": "business"
   },
   {
    "id": "FR-001",
    "page": "functional"
   },
   {
    "id": "FR-051",
    "page": "functional"
   },
   {
    "id": "FR-058",
    "page": "functional"
   },
   {
    "id": "FR-062",
    "page": "functional"
   },
   {
    "id": "FR-095",
    "page": "functional"
   },
   {
    "id": "NFR-A-006",
    "page": "quality"
   },
   {
    "id": "NFR-SEC-009",
    "page": "quality"
   },
   {
    "id": "NFR-I-005",
    "page": "quality"
   }
  ],
  "human-dm": [
   {
    "id": "BR-005",
    "page": "business"
   },
   {
    "id": "FR-003",
    "page": "functional"
   }
  ],
  "sharing-agreement": [
   {
    "id": "BR-006",
    "page": "business"
   },
   {
    "id": "BR-008",
    "page": "business"
   },
   {
    "id": "FR-085",
    "page": "functional"
   }
  ],
  "bcea-manual": [
   {
    "id": "BR-007",
    "page": "business"
   },
   {
    "id": "BR-013",
    "page": "business"
   },
   {
    "id": "BR-014",
    "page": "business"
   }
  ],
  "control-totals": [
   {
    "id": "BR-007",
    "page": "business"
   },
   {
    "id": "FR-043",
    "page": "functional"
   },
   {
    "id": "NFR-C-003",
    "page": "quality"
   },
   {
    "id": "NFR-M-003",
    "page": "quality"
   },
   {
    "id": "DR-004",
    "page": "data"
   }
  ],
  "ima": [
   {
    "id": "BR-007",
    "page": "business"
   },
   {
    "id": "NFR-C-003",
    "page": "quality"
   },
   {
    "id": "DR-004",
    "page": "data"
   }
  ],
  "custodian": [
   {
    "id": "BR-008",
    "page": "business"
   },
   {
    "id": "FR-084",
    "page": "functional"
   },
   {
    "id": "NFR-SEC-005",
    "page": "quality"
   },
   {
    "id": "NFR-C-007",
    "page": "quality"
   },
   {
    "id": "DR-005",
    "page": "data"
   }
  ],
  "decision-trace": [
   {
    "id": "BR-008",
    "page": "business"
   },
   {
    "id": "FR-002",
    "page": "functional"
   }
  ],
  "dripa": [
   {
    "id": "BR-008",
    "page": "business"
   }
  ],
  "accessibility-standard": [
   {
    "id": "BR-009",
    "page": "business"
   },
   {
    "id": "NFR-U-002",
    "page": "quality"
   }
  ],
  "assistive-technology": [
   {
    "id": "BR-009",
    "page": "business"
   },
   {
    "id": "NFR-U-002",
    "page": "quality"
   }
  ],
  "duty-accommodate": [
   {
    "id": "BR-009",
    "page": "business"
   },
   {
    "id": "FR-087",
    "page": "functional"
   }
  ],
  "aggregate": [
   {
    "id": "BR-011",
    "page": "business"
   },
   {
    "id": "FR-006",
    "page": "functional"
   },
   {
    "id": "FR-041",
    "page": "functional"
   },
   {
    "id": "NFR-SEC-011",
    "page": "quality"
   },
   {
    "id": "DR-020",
    "page": "data"
   }
  ],
  "client-group": [
   {
    "id": "BR-011",
    "page": "business"
   },
   {
    "id": "NFR-P-005",
    "page": "quality"
   },
   {
    "id": "NFR-A-008",
    "page": "quality"
   },
   {
    "id": "INT-023",
    "page": "integrations"
   }
  ],
  "design-freeze": [
   {
    "id": "BR-013",
    "page": "business"
   },
   {
    "id": "NFR-P-001",
    "page": "quality"
   },
   {
    "id": "NFR-S-001",
    "page": "quality"
   }
  ],
  "obligation": [
   {
    "id": "BR-013",
    "page": "business"
   }
  ],
  "payment-instruction": [
   {
    "id": "BR-013",
    "page": "business"
   },
   {
    "id": "FR-033",
    "page": "functional"
   },
   {
    "id": "FR-042",
    "page": "functional"
   },
   {
    "id": "NFR-A-002",
    "page": "quality"
   },
   {
    "id": "INT-017",
    "page": "integrations"
   }
  ],
  "tier1": [
   {
    "id": "BR-013",
    "page": "business"
   },
   {
    "id": "NFR-A-002",
    "page": "quality"
   },
   {
    "id": "NFR-M-006",
    "page": "quality"
   }
  ],
  "program-policy-authority": [
   {
    "id": "BR-014",
    "page": "business"
   },
   {
    "id": "FR-003",
    "page": "functional"
   }
  ],
  "rules-register": [
   {
    "id": "BR-014",
    "page": "business"
   },
   {
    "id": "FR-010",
    "page": "functional"
   },
   {
    "id": "FR-016",
    "page": "functional"
   },
   {
    "id": "FR-037",
    "page": "functional"
   },
   {
    "id": "FR-048",
    "page": "functional"
   }
  ],
  "determination": [
   {
    "id": "FR-001",
    "page": "functional"
   },
   {
    "id": "FR-011",
    "page": "functional"
   },
   {
    "id": "FR-025",
    "page": "functional"
   },
   {
    "id": "FR-042",
    "page": "functional"
   },
   {
    "id": "FR-051",
    "page": "functional"
   },
   {
    "id": "FR-057",
    "page": "functional"
   },
   {
    "id": "FR-062",
    "page": "functional"
   },
   {
    "id": "FR-073",
    "page": "functional"
   },
   {
    "id": "FR-080",
    "page": "functional"
   },
   {
    "id": "FR-090",
    "page": "functional"
   },
   {
    "id": "FR-095",
    "page": "functional"
   },
   {
    "id": "NFR-P-001",
    "page": "quality"
   },
   {
    "id": "NFR-A-001",
    "page": "quality"
   },
   {
    "id": "NFR-S-001",
    "page": "quality"
   },
   {
    "id": "NFR-SEC-005",
    "page": "quality"
   },
   {
    "id": "NFR-C-005",
    "page": "quality"
   },
   {
    "id": "NFR-M-006",
    "page": "quality"
   },
   {
    "id": "NFR-I-002",
    "page": "quality"
   },
   {
    "id": "INT-001",
    "page": "integrations"
   }
  ],
  "rules-engine": [
   {
    "id": "FR-001",
    "page": "functional"
   },
   {
    "id": "FR-061",
    "page": "functional"
   },
   {
    "id": "FR-090",
    "page": "functional"
   },
   {
    "id": "FR-095",
    "page": "functional"
   }
  ],
  "watermark": [
   {
    "id": "FR-001",
    "page": "functional"
   },
   {
    "id": "FR-058",
    "page": "functional"
   },
   {
    "id": "NFR-P-004",
    "page": "quality"
   }
  ],
  "decision-class": [
   {
    "id": "FR-003",
    "page": "functional"
   }
  ],
  "benefit-component": [
   {
    "id": "FR-005",
    "page": "functional"
   }
  ],
  "adjudicability": [
   {
    "id": "FR-006",
    "page": "functional"
   },
   {
    "id": "FR-030",
    "page": "functional"
   },
   {
    "id": "FR-033",
    "page": "functional"
   },
   {
    "id": "FR-056",
    "page": "functional"
   },
   {
    "id": "FR-063",
    "page": "functional"
   },
   {
    "id": "FR-092",
    "page": "functional"
   }
  ],
  "pre-decision": [
   {
    "id": "FR-006",
    "page": "functional"
   }
  ],
  "hash-chain": [
   {
    "id": "FR-008",
    "page": "functional"
   },
   {
    "id": "NFR-SEC-009",
    "page": "quality"
   },
   {
    "id": "NFR-C-002",
    "page": "quality"
   }
  ],
  "regression-corpus": [
   {
    "id": "FR-008",
    "page": "functional"
   },
   {
    "id": "FR-090",
    "page": "functional"
   }
  ],
  "shred-survivor": [
   {
    "id": "FR-008",
    "page": "functional"
   },
   {
    "id": "FR-077",
    "page": "functional"
   },
   {
    "id": "NFR-C-003",
    "page": "quality"
   },
   {
    "id": "DR-004",
    "page": "data"
   }
  ],
  "work-item": [
   {
    "id": "FR-009",
    "page": "functional"
   },
   {
    "id": "FR-014",
    "page": "functional"
   },
   {
    "id": "FR-028",
    "page": "functional"
   },
   {
    "id": "FR-038",
    "page": "functional"
   },
   {
    "id": "FR-044",
    "page": "functional"
   },
   {
    "id": "FR-059",
    "page": "functional"
   },
   {
    "id": "FR-067",
    "page": "functional"
   },
   {
    "id": "FR-071",
    "page": "functional"
   },
   {
    "id": "FR-082",
    "page": "functional"
   },
   {
    "id": "FR-089",
    "page": "functional"
   },
   {
    "id": "NFR-A-004",
    "page": "quality"
   },
   {
    "id": "NFR-U-001",
    "page": "quality"
   },
   {
    "id": "INT-002",
    "page": "integrations"
   },
   {
    "id": "DR-018",
    "page": "data"
   }
  ],
  "cihr": [
   {
    "id": "FR-010",
    "page": "functional"
   },
   {
    "id": "FR-023",
    "page": "functional"
   },
   {
    "id": "INT-013",
    "page": "integrations"
   }
  ],
  "asserted-negative": [
   {
    "id": "FR-011",
    "page": "functional"
   },
   {
    "id": "DR-002",
    "page": "data"
   }
  ],
  "correction": [
   {
    "id": "FR-012",
    "page": "functional"
   },
   {
    "id": "FR-051",
    "page": "functional"
   },
   {
    "id": "DR-001",
    "page": "data"
   },
   {
    "id": "DR-015",
    "page": "data"
   }
  ],
  "succession-set": [
   {
    "id": "FR-012",
    "page": "functional"
   },
   {
    "id": "NFR-A-009",
    "page": "quality"
   },
   {
    "id": "DR-020",
    "page": "data"
   }
  ],
  "fact": [
   {
    "id": "FR-014",
    "page": "functional"
   },
   {
    "id": "FR-073",
    "page": "functional"
   },
   {
    "id": "NFR-A-002",
    "page": "quality"
   }
  ],
  "rdsp": [
   {
    "id": "FR-017",
    "page": "functional"
   }
  ],
  "modern-treaty": [
   {
    "id": "FR-021",
    "page": "functional"
   },
   {
    "id": "INT-012",
    "page": "integrations"
   }
  ],
  "calendar-basis": [
   {
    "id": "FR-024",
    "page": "functional"
   },
   {
    "id": "FR-039",
    "page": "functional"
   },
   {
    "id": "FR-061",
    "page": "functional"
   }
  ],
  "federal-benefits": [
   {
    "id": "FR-027",
    "page": "functional"
   },
   {
    "id": "NFR-P-001",
    "page": "quality"
   },
   {
    "id": "INT-007",
    "page": "integrations"
   }
  ],
  "identity-assurance": [
   {
    "id": "FR-027",
    "page": "functional"
   },
   {
    "id": "FR-088",
    "page": "functional"
   },
   {
    "id": "NFR-SEC-001",
    "page": "quality"
   },
   {
    "id": "INT-005",
    "page": "integrations"
   }
  ],
  "client-index": [
   {
    "id": "FR-028",
    "page": "functional"
   },
   {
    "id": "INT-016",
    "page": "integrations"
   },
   {
    "id": "DR-019",
    "page": "data"
   }
  ],
  "ea-acts": [
   {
    "id": "FR-030",
    "page": "functional"
   }
  ],
  "prescribed-class": [
   {
    "id": "FR-030",
    "page": "functional"
   }
  ],
  "pbc-clbc": [
   {
    "id": "FR-036",
    "page": "functional"
   },
   {
    "id": "FR-058",
    "page": "functional"
   },
   {
    "id": "INT-009",
    "page": "integrations"
   }
  ],
  "repayable": [
   {
    "id": "FR-041",
    "page": "functional"
   }
  ],
  "issuance-service": [
   {
    "id": "FR-042",
    "page": "functional"
   },
   {
    "id": "FR-060",
    "page": "functional"
   },
   {
    "id": "FR-097",
    "page": "functional"
   },
   {
    "id": "NFR-M-006",
    "page": "quality"
   },
   {
    "id": "INT-001",
    "page": "integrations"
   }
  ],
  "deidentified": [
   {
    "id": "FR-045",
    "page": "functional"
   },
   {
    "id": "NFR-P-002",
    "page": "quality"
   },
   {
    "id": "NFR-SEC-012",
    "page": "quality"
   },
   {
    "id": "NFR-C-004",
    "page": "quality"
   },
   {
    "id": "DR-017",
    "page": "data"
   }
  ],
  "ledger": [
   {
    "id": "FR-045",
    "page": "functional"
   },
   {
    "id": "FR-053",
    "page": "functional"
   },
   {
    "id": "NFR-U-002",
    "page": "quality"
   }
  ],
  "discretionary": [
   {
    "id": "FR-047",
    "page": "functional"
   }
  ],
  "emergency-issuance": [
   {
    "id": "FR-047",
    "page": "functional"
   },
   {
    "id": "NFR-C-008",
    "page": "quality"
   }
  ],
  "rollback": [
   {
    "id": "FR-047",
    "page": "functional"
   },
   {
    "id": "NFR-A-006",
    "page": "quality"
   },
   {
    "id": "NFR-M-006",
    "page": "quality"
   },
   {
    "id": "DR-015",
    "page": "data"
   }
  ],
  "system-of-record": [
   {
    "id": "FR-047",
    "page": "functional"
   },
   {
    "id": "NFR-A-009",
    "page": "quality"
   },
   {
    "id": "NFR-SEC-003",
    "page": "quality"
   }
  ],
  "set-off": [
   {
    "id": "FR-048",
    "page": "functional"
   },
   {
    "id": "FR-052",
    "page": "functional"
   },
   {
    "id": "FR-060",
    "page": "functional"
   },
   {
    "id": "INT-007",
    "page": "integrations"
   }
  ],
  "overpayment": [
   {
    "id": "FR-051",
    "page": "functional"
   },
   {
    "id": "DR-013",
    "page": "data"
   }
  ],
  "adjudicating-authority": [
   {
    "id": "FR-056",
    "page": "functional"
   }
  ],
  "foippa": [
   {
    "id": "FR-058",
    "page": "functional"
   },
   {
    "id": "FR-076",
    "page": "functional"
   },
   {
    "id": "NFR-C-001",
    "page": "quality"
   }
  ],
  "invalidation": [
   {
    "id": "FR-059",
    "page": "functional"
   },
   {
    "id": "DR-002",
    "page": "data"
   }
  ],
  "clock-class": [
   {
    "id": "FR-061",
    "page": "functional"
   }
  ],
  "legal-time-limit": [
   {
    "id": "FR-061",
    "page": "functional"
   },
   {
    "id": "INT-011",
    "page": "integrations"
   }
  ],
  "deemed-receipt": [
   {
    "id": "FR-064",
    "page": "functional"
   },
   {
    "id": "INT-003",
    "page": "integrations"
   }
  ],
  "disposition": [
   {
    "id": "FR-072",
    "page": "functional"
   },
   {
    "id": "FR-096",
    "page": "functional"
   },
   {
    "id": "NFR-C-003",
    "page": "quality"
   }
  ],
  "non-crown": [
   {
    "id": "FR-085",
    "page": "functional"
   },
   {
    "id": "INT-012",
    "page": "integrations"
   }
  ],
  "interface": [
   {
    "id": "FR-086",
    "page": "functional"
   },
   {
    "id": "NFR-P-001",
    "page": "quality"
   },
   {
    "id": "NFR-A-001",
    "page": "quality"
   },
   {
    "id": "NFR-M-001",
    "page": "quality"
   },
   {
    "id": "NFR-I-002",
    "page": "quality"
   },
   {
    "id": "INT-020",
    "page": "integrations"
   }
  ],
  "pure": [
   {
    "id": "FR-090",
    "page": "functional"
   }
  ],
  "statutory-dm": [
   {
    "id": "FR-093",
    "page": "functional"
   }
  ],
  "lakehouse": [
   {
    "id": "FR-096",
    "page": "functional"
   }
  ],
  "pci": [
   {
    "id": "FR-097",
    "page": "functional"
   },
   {
    "id": "INT-025",
    "page": "integrations"
   }
  ],
  "target-architecture": [
   {
    "id": "FR-099",
    "page": "functional"
   }
  ],
  "circuit-breaker": [
   {
    "id": "NFR-P-001",
    "page": "quality"
   },
   {
    "id": "NFR-A-003",
    "page": "quality"
   }
  ],
  "event": [
   {
    "id": "NFR-P-001",
    "page": "quality"
   },
   {
    "id": "NFR-A-006",
    "page": "quality"
   },
   {
    "id": "NFR-SEC-009",
    "page": "quality"
   },
   {
    "id": "NFR-M-001",
    "page": "quality"
   },
   {
    "id": "NFR-I-004",
    "page": "quality"
   },
   {
    "id": "INT-023",
    "page": "integrations"
   }
  ],
  "p95": [
   {
    "id": "NFR-P-001",
    "page": "quality"
   },
   {
    "id": "NFR-M-002",
    "page": "quality"
   }
  ],
  "telemetry": [
   {
    "id": "NFR-P-001",
    "page": "quality"
   },
   {
    "id": "NFR-C-004",
    "page": "quality"
   },
   {
    "id": "NFR-M-001",
    "page": "quality"
   }
  ],
  "translation-layer": [
   {
    "id": "NFR-P-001",
    "page": "quality"
   },
   {
    "id": "NFR-A-008",
    "page": "quality"
   },
   {
    "id": "NFR-I-001",
    "page": "quality"
   },
   {
    "id": "INT-023",
    "page": "integrations"
   }
  ],
  "three-way": [
   {
    "id": "NFR-P-002",
    "page": "quality"
   }
  ],
  "headroom": [
   {
    "id": "NFR-P-003",
    "page": "quality"
   },
   {
    "id": "NFR-S-001",
    "page": "quality"
   }
  ],
  "partition": [
   {
    "id": "NFR-P-006",
    "page": "quality"
   }
  ],
  "protected-abc": [
   {
    "id": "NFR-P-006",
    "page": "quality"
   },
   {
    "id": "NFR-A-009",
    "page": "quality"
   },
   {
    "id": "NFR-C-001",
    "page": "quality"
   },
   {
    "id": "INT-001",
    "page": "integrations"
   },
   {
    "id": "DR-003",
    "page": "data"
   }
  ],
  "recovery-targets": [
   {
    "id": "NFR-A-002",
    "page": "quality"
   }
  ],
  "release-train": [
   {
    "id": "NFR-A-002",
    "page": "quality"
   }
  ],
  "automated-check": [
   {
    "id": "NFR-A-003",
    "page": "quality"
   },
   {
    "id": "NFR-M-004",
    "page": "quality"
   },
   {
    "id": "DR-007",
    "page": "data"
   }
  ],
  "degraded-mode": [
   {
    "id": "NFR-A-003",
    "page": "quality"
   }
  ],
  "idempotent": [
   {
    "id": "NFR-A-003",
    "page": "quality"
   },
   {
    "id": "NFR-I-004",
    "page": "quality"
   }
  ],
  "sync": [
   {
    "id": "NFR-A-003",
    "page": "quality"
   }
  ],
  "active-active": [
   {
    "id": "NFR-A-004",
    "page": "quality"
   }
  ],
  "availability-target": [
   {
    "id": "NFR-A-007",
    "page": "quality"
   },
   {
    "id": "INT-005",
    "page": "integrations"
   }
  ],
  "part": [
   {
    "id": "NFR-A-009",
    "page": "quality"
   },
   {
    "id": "NFR-SEC-008",
    "page": "quality"
   }
  ],
  "key-destruction": [
   {
    "id": "NFR-S-002",
    "page": "quality"
   },
   {
    "id": "NFR-SEC-005",
    "page": "quality"
   },
   {
    "id": "DR-004",
    "page": "data"
   }
  ],
  "separate-storage": [
   {
    "id": "NFR-S-002",
    "page": "quality"
   },
   {
    "id": "DR-004",
    "page": "data"
   }
  ],
  "bceid": [
   {
    "id": "NFR-SEC-001",
    "page": "quality"
   },
   {
    "id": "INT-005",
    "page": "integrations"
   }
  ],
  "bff": [
   {
    "id": "NFR-SEC-001",
    "page": "quality"
   },
   {
    "id": "INT-005",
    "page": "integrations"
   }
  ],
  "oidc": [
   {
    "id": "NFR-SEC-001",
    "page": "quality"
   },
   {
    "id": "INT-005",
    "page": "integrations"
   }
  ],
  "api": [
   {
    "id": "NFR-SEC-002",
    "page": "quality"
   },
   {
    "id": "NFR-I-003",
    "page": "quality"
   },
   {
    "id": "INT-003",
    "page": "integrations"
   }
  ],
  "ci": [
   {
    "id": "NFR-SEC-002",
    "page": "quality"
   },
   {
    "id": "NFR-U-002",
    "page": "quality"
   },
   {
    "id": "NFR-M-004",
    "page": "quality"
   },
   {
    "id": "NFR-I-002",
    "page": "quality"
   }
  ],
  "break-glass": [
   {
    "id": "NFR-SEC-004",
    "page": "quality"
   }
  ],
  "slo": [
   {
    "id": "NFR-SEC-004",
    "page": "quality"
   },
   {
    "id": "NFR-M-001",
    "page": "quality"
   }
  ],
  "mtls": [
   {
    "id": "NFR-SEC-005",
    "page": "quality"
   },
   {
    "id": "INT-001",
    "page": "integrations"
   }
  ],
  "sbom": [
   {
    "id": "NFR-SEC-007",
    "page": "quality"
   },
   {
    "id": "NFR-C-006",
    "page": "quality"
   }
  ],
  "threat-model": [
   {
    "id": "NFR-SEC-008",
    "page": "quality"
   },
   {
    "id": "NFR-C-006",
    "page": "quality"
   },
   {
    "id": "NFR-M-006",
    "page": "quality"
   }
  ],
  "correlation-id": [
   {
    "id": "NFR-SEC-010",
    "page": "quality"
   },
   {
    "id": "NFR-C-001",
    "page": "quality"
   },
   {
    "id": "NFR-M-001",
    "page": "quality"
   }
  ],
  "evidence-tier": [
   {
    "id": "NFR-SEC-010",
    "page": "quality"
   },
   {
    "id": "INT-022",
    "page": "integrations"
   }
  ],
  "write-back": [
   {
    "id": "NFR-SEC-011",
    "page": "quality"
   },
   {
    "id": "NFR-M-003",
    "page": "quality"
   },
   {
    "id": "INT-023",
    "page": "integrations"
   },
   {
    "id": "DR-014",
    "page": "data"
   }
  ],
  "tombstone": [
   {
    "id": "NFR-C-003",
    "page": "quality"
   },
   {
    "id": "DR-004",
    "page": "data"
   }
  ],
  "copy": [
   {
    "id": "NFR-C-004",
    "page": "quality"
   }
  ],
  "shadow-root": [
   {
    "id": "NFR-U-004",
    "page": "quality"
   }
  ],
  "component-library": [
   {
    "id": "NFR-U-005",
    "page": "quality"
   }
  ],
  "excision-test": [
   {
    "id": "NFR-I-001",
    "page": "quality"
   }
  ],
  "schema": [
   {
    "id": "NFR-I-003",
    "page": "quality"
   }
  ],
  "tribunal": [
   {
    "id": "INT-011",
    "page": "integrations"
   }
  ],
  "cfcsa": [
   {
    "id": "INT-013",
    "page": "integrations"
   }
  ],
  "delegated-agency": [
   {
    "id": "INT-013",
    "page": "integrations"
   }
  ],
  "secure-data-exchange": [
   {
    "id": "INT-013",
    "page": "integrations"
   }
  ],
  "pcms": [
   {
    "id": "INT-020",
    "page": "integrations"
   }
  ],
  "fmep": [
   {
    "id": "INT-024",
    "page": "integrations"
   }
  ],
  "valid-time": [
   {
    "id": "DR-001",
    "page": "data"
   },
   {
    "id": "DR-010",
    "page": "data"
   }
  ],
  "not-retainable": [
   {
    "id": "DR-002",
    "page": "data"
   }
  ],
  "replay-horizon": [
   {
    "id": "DR-008",
    "page": "data"
   }
  ],
  "provenance": [
   {
    "id": "DR-010",
    "page": "data"
   }
  ],
  "temporally-unverified": [
   {
    "id": "DR-013",
    "page": "data"
   }
  ],
  "capture": [
   {
    "id": "DR-014",
    "page": "data"
   }
  ]
 }
};
