// Generated by scripts/build-requirements.py from the requirements specification. Do not edit by hand.
export default {
 "intro": "<p>Three rules apply to every integration below. They are not repeated in each entry.</p><p>1. <strong>An integration that is not in the Module 0 integration inventory is not authorised to exist</strong> <span class=\"cite\">TA-C42</span>. Each entry here becomes one or more named rows in that inventory, using the columns in TA §C.13.2: system, counterparty and accountable role, direction, pattern, classification, legal basis, criticality and <a class=\"g\" href=\"%BASE%/glossary#disposition\">disposition</a>. The Programme Chief Architect owns the inventory, and it is due by month 4 of Module 0. 2. <strong>Every integration has a legal basis recorded</strong> in the <a class=\"g\" href=\"%BASE%/glossary#sharing-agreement\">agreement registry</a> (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-085\">FR-085</a>). An integration without one is unauthorised, whatever it does today. 3. <strong>No interactive path depends <a class=\"g\" href=\"%BASE%/glossary#sync\">synchronously</a> on more than one external participant</strong> (<a class=\"rid\" href=\"%BASE%/requirements/quality#nfr-a-004\">NFR-A-004</a>). Where an entry says \"asynchronous\", this rule is why. Where no source states a service level, the entry says \"not stated\". The design then assumes the exchange is not on a path a worker waits on, until the counterparty commits to a figure in writing.</p><p>Details marked <strong>[U]</strong> are unverified in the architecture's own register. They are settled in the inventory, not here.</p>",
 "groups": [
  {
   "id": "external-system-integrations",
   "title": "External integrations",
   "intro": "",
   "items": [
    {
     "id": "INT-001",
     "anchor": "int-001",
     "title": "Corporate Accounting System",
     "priority": "Must",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "Post payments, reversals, amounts owed to the ministry, recoveries and write-offs to the book of record, and reconcile daily and at month-end.",
     "fields": [
      {
       "label": "Purpose",
       "html": "<p>Post payments, reversals, amounts owed to the ministry, recoveries and write-offs to the book of record, and reconcile daily and at month-end.</p>"
      },
      {
       "label": "Integration Type",
       "html": "<p>Batch posting and reconciliation query</p>"
      },
      {
       "label": "Data Exchanged",
       "html": "<ul><li><strong>From this system to CAS</strong>: postings with coding block, <a class=\"g\" href=\"%BASE%/glossary#determination\">determination</a> reference and run identifier; supplier records for provider payments.</li><li><strong>From CAS to this system</strong>: the posted position, rejections, the month-end calendar and blackout periods.</li></ul>"
      },
      {
       "label": "Integration Pattern",
       "html": "<p>Only through the <a class=\"g\" href=\"%BASE%/glossary#issuance-service\">Issuance Service</a> (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-042\">FR-042</a>). No other component holds a posting credential.</p>"
      },
      {
       "label": "Authentication",
       "html": "<p>A service credential held only by the Issuance Service, over <a class=\"g\" href=\"%BASE%/glossary#mtls\">mutual TLS</a>.</p>"
      },
      {
       "label": "Error Handling",
       "html": "<p><a class=\"g\" href=\"%BASE%/glossary#cas\">CAS</a> rejects some batches as a whole when supplier key fields are missing (APP-R8). Supplier keys are therefore checked before submission. A rejection becomes a reconciliation break with an owner and an age. It is never retried silently.</p>"
      },
      {
       "label": "SLA",
       "html": "<p>Daily reconciliation. Postings are queued during blackouts (<a class=\"rid\" href=\"%BASE%/requirements/quality#nfr-a-005\">NFR-A-005</a>). Today CAS offers only file-availability windows. The cutoff calendar is still to be confirmed by the Executive Financial Officer.</p>"
      },
      {
       "label": "Owner",
       "html": "<p>Provincial corporate financial function; ministry Executive Financial Officer.</p>"
      },
      {
       "label": "Classification",
       "html": "<p><a class=\"g\" href=\"%BASE%/glossary#protected-abc\">Protected B</a></p>"
      },
      {
       "label": "Rationale",
       "html": "<p>The corporate financial system remains the book of record (TA §C.6.4). CAS is outside the replacement scope, so the new system must connect to it (APP §1.1).</p>"
      }
     ]
    },
    {
     "id": "INT-002",
     "anchor": "int-002",
     "title": "Bank and electronic funds transfer",
     "priority": "Must",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "Pay by direct deposit;",
     "fields": [
      {
       "label": "Purpose",
       "html": "<p>Pay by direct deposit; receive settlement, return and reject files; run payment traces; receive client debt repayments.</p>"
      },
      {
       "label": "Integration Type",
       "html": "<p>Batch file transfer</p>"
      },
      {
       "label": "Data Exchanged",
       "html": "<ul><li><strong>Outbound</strong>: payment files in the format the bank requires; trace requests.</li><li><strong>Inbound</strong>: settlement confirmations, returns, rejects, trace results and repayment files.</li></ul>"
      },
      {
       "label": "Integration Pattern",
       "html": "<p>Through the Issuance Service only. A missing inbound file raises an alarm.</p>"
      },
      {
       "label": "Authentication",
       "html": "<p>Mutual TLS and file signing, as the bank requires.</p>"
      },
      {
       "label": "Error Handling",
       "html": "<p>A returned payment reopens the entitlement and queues a <a class=\"g\" href=\"%BASE%/glossary#work-item\">work item</a> (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-044\">FR-044</a>). A missing file raises an alarm.</p>"
      },
      {
       "label": "SLA",
       "html": "<p>Settlement within the bank's stated window. The maximum reconciliation lag is stated for each payment channel.</p>"
      },
      {
       "label": "Owner",
       "html": "<p>The settlement institution; ministry payment operations lead.</p>"
      },
      {
       "label": "Classification",
       "html": "<p>Protected B</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>Payment is the most critical integration (TA §C.13.3).</p>"
      }
     ]
    },
    {
     "id": "INT-003",
     "anchor": "int-003",
     "title": "Provincial print-and-mail and cheque printing",
     "priority": "Must",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "Print and mail notices, letters and booklets;",
     "fields": [
      {
       "label": "Purpose",
       "html": "<p>Print and mail notices, letters and booklets; print cheques; receive returned mail and delivery confirmations.</p>"
      },
      {
       "label": "Integration Type",
       "html": "<p>Batch file transfer (assumed, because no public <a class=\"g\" href=\"%BASE%/glossary#api\">API</a> specification has been found [U])</p>"
      },
      {
       "label": "Data Exchanged",
       "html": "<ul><li><strong>Outbound</strong>: rendered documents with delivery details; cheque print files drawn from a controlled range of cheque numbers.</li><li><strong>Inbound</strong>: confirmations that mail was lodged; returned mail.</li></ul>"
      },
      {
       "label": "Integration Pattern",
       "html": "<p>Notices go through Notices &amp; Correspondence. Cheques go through the Issuance Service.</p>"
      },
      {
       "label": "Authentication",
       "html": "<p>SFTP with service credentials, to be confirmed with the service.</p>"
      },
      {
       "label": "Error Handling",
       "html": "<p>Returned mail updates the delivery record and raises a work item. <a class=\"g\" href=\"%BASE%/glossary#deemed-receipt\">Deemed receipt</a> is calculated by rule (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-064\">FR-064</a>), never typed in.</p>"
      },
      {
       "label": "SLA",
       "html": "<p>The file delivery windows the service sets.</p>"
      },
      {
       "label": "Owner",
       "html": "<p>Provincial print-and-mail service; ministry correspondence business owner.</p>"
      },
      {
       "label": "Classification",
       "html": "<p>Protected B/C</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>Notices and cheques go through this service today, over 10 named interfaces (APP §4.2).</p>"
      }
     ]
    },
    {
     "id": "INT-004",
     "anchor": "int-004",
     "title": "Provincial notification service",
     "priority": "Must",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "Send notices and messages electronically, and receive delivery confirmations.",
     "fields": [
      {
       "label": "Purpose",
       "html": "<p>Send notices and messages electronically, and receive delivery confirmations.</p>"
      },
      {
       "label": "Integration Type",
       "html": "<p>API</p>"
      },
      {
       "label": "Data Exchanged",
       "html": "<ul><li><strong>Outbound</strong>: messages and notice references.</li><li><strong>Inbound</strong>: delivery events.</li></ul>"
      },
      {
       "label": "Integration Pattern",
       "html": "<p>Asynchronous. The service is used as it is. If it is not ready in time for correspondence capture, a named and funded fallback takes over: the federal notification platform or the provincial common hosted email service.</p>"
      },
      {
       "label": "Authentication",
       "html": "<p>OAuth 2.0 client credentials, as the service requires.</p>"
      },
      {
       "label": "Error Handling",
       "html": "<p>If electronic delivery fails, the notice goes by the client's next preferred channel.</p>"
      },
      {
       "label": "SLA",
       "html": "<p>Not stated. To be confirmed against the correspondence capture date.</p>"
      },
      {
       "label": "Owner",
       "html": "<p>Provincial notification platform; Chief Digital Officer.</p>"
      },
      {
       "label": "Classification",
       "html": "<p>Protected A/B</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>The system reuses the provincial service, but the service is still being built, so it is treated as a dependency (TA §C.18).</p>"
      }
     ]
    },
    {
     "id": "INT-005",
     "anchor": "int-005",
     "title": "Provincial identity services",
     "priority": "Must",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "Sign in workers, citizens, businesses and partners.",
     "fields": [
      {
       "label": "Purpose",
       "html": "<p>Sign in workers, citizens, businesses and partners. Exchange tokens across organisational boundaries so that the legal basis for an exchange travels with the request.</p>"
      },
      {
       "label": "Integration Type",
       "html": "<p>Real-time <a class=\"g\" href=\"%BASE%/glossary#oidc\">OIDC</a></p>"
      },
      {
       "label": "Data Exchanged",
       "html": "<ul><li><strong>From the identity provider</strong>: signed-in identities and their assurance levels (the corporate directory with multi-factor authentication, the BC Services Card at <a class=\"g\" href=\"%BASE%/glossary#identity-assurance\">assurance level</a> 3, and <a class=\"g\" href=\"%BASE%/glossary#bceid\">BCeID</a>).</li><li><strong>Token exchange (RFC 8693)</strong> and <strong>rich authorization requests (RFC 9396)</strong>, which carry the agreement identifier and the legal authority relied on.</li></ul>"
      },
      {
       "label": "Integration Pattern",
       "html": "<p>A <a class=\"g\" href=\"%BASE%/glossary#bff\">back end for front end</a> for each experience. Tokens are delegated, never impersonated.</p>"
      },
      {
       "label": "Authentication",
       "html": "<p>OIDC confidential clients.</p>"
      },
      {
       "label": "Error Handling",
       "html": "<p>Every channel depends on this service, so its availability counts in the <a class=\"g\" href=\"%BASE%/glossary#availability-target\">combined availability</a> arithmetic (<a class=\"rid\" href=\"%BASE%/requirements/quality#nfr-a-001\">NFR-A-001</a>).</p>"
      },
      {
       "label": "SLA",
       "html": "<p>Highly available across sites [V as at January 2026]. It is unconfirmed whether the <strong>deployed</strong> version supports token exchange and rich authorization requests [U]. The ministry CTO checks this within 60 days of programme start.</p>"
      },
      {
       "label": "Owner",
       "html": "<p>Provincial identity service; ministry CTO.</p>"
      },
      {
       "label": "Classification",
       "html": "<p>Not applicable</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>Rich authorization requests are what carry the legal basis, and they still have to be built (TA §C.3.3).</p>"
      }
     ]
    },
    {
     "id": "INT-006",
     "anchor": "int-006",
     "title": "Canada Revenue Agency",
     "priority": "Must",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "Check income and tax information for eligibility and overpayments, with valid consent.",
     "fields": [
      {
       "label": "Purpose",
       "html": "<p>Check income and tax information for eligibility and overpayments, with valid consent.</p>"
      },
      {
       "label": "Integration Type",
       "html": "<p>Batch file transfer, consent-based query, or both [U]</p>"
      },
      {
       "label": "Data Exchanged",
       "html": "<ul><li><strong>Inbound</strong>: taxpayer information, as consented. It is <strong>not printed or kept</strong> as a document (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-011\">FR-011</a>).</li><li><strong>Outbound</strong>: requests that carry a consent reference.</li></ul>"
      },
      {
       "label": "Integration Pattern",
       "html": "<p>Asynchronous. Consent is checked before every request (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-015\">FR-015</a>).</p>"
      },
      {
       "label": "Authentication",
       "html": "<p>As the agreement specifies [U].</p>"
      },
      {
       "label": "Error Handling",
       "html": "<p>If no response arrives, the check is deferred. The determination then follows the policy on deferral. The system never fills in a value.</p>"
      },
      {
       "label": "SLA",
       "html": "<p>Twice-daily batch today. Not stated for the new system.</p>"
      },
      {
       "label": "Owner",
       "html": "<p>Federal revenue agency; the ministry business owner named in the inventory.</p>"
      },
      {
       "label": "Classification",
       "html": "<p>Protected B/C</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>This information drives eligibility and overpayment decisions (TA §C.13.3).</p>"
      }
     ]
    },
    {
     "id": "INT-007",
     "anchor": "int-007",
     "title": "Employment and Social Development Canada and Service Canada",
     "priority": "Must",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "Exchange CPP, OAS/GIS and EI information;",
     "fields": [
      {
       "label": "Purpose",
       "html": "<p>Exchange <a class=\"g\" href=\"%BASE%/glossary#federal-benefits\">CPP</a>, OAS/GIS and EI information; verify social insurance numbers; support assignments and consents to deduction.</p>"
      },
      {
       "label": "Integration Type",
       "html": "<p>Batch and query [U]</p>"
      },
      {
       "label": "Data Exchanged",
       "html": "<ul><li><strong>Inbound</strong>: federal benefit status and amounts; SIN verification.</li><li><strong>Outbound</strong>: requests, assignments and deduction consents.</li></ul>"
      },
      {
       "label": "Integration Pattern",
       "html": "<p>Asynchronous. Volumes include a CPP request file of about 250,000 records (APP §10).</p>"
      },
      {
       "label": "Authentication",
       "html": "<p>As the agreement specifies [U].</p>"
      },
      {
       "label": "Error Handling",
       "html": "<p>A failed file raises an alarm. No deduction is applied without a confirmed consent.</p>"
      },
      {
       "label": "SLA",
       "html": "<p>Not stated.</p>"
      },
      {
       "label": "Owner",
       "html": "<p>Federal benefits administrator; the ministry business owner named in the inventory.</p>"
      },
      {
       "label": "Classification",
       "html": "<p>Protected B/C</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>Entitlement and <a class=\"g\" href=\"%BASE%/glossary#set-off\">set-off</a> both depend on federal income benefits (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-018\">FR-018</a>).</p>"
      }
     ]
    },
    {
     "id": "INT-008",
     "anchor": "int-008",
     "title": "Provincial health insurance and health data",
     "priority": "Should",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "Enrol recipients in health coverage, confirm coverage status, and exchange health identity and pharmacare information.",
     "fields": [
      {
       "label": "Purpose",
       "html": "<p>Enrol recipients in health coverage, confirm coverage status, and exchange health identity and pharmacare information.</p>"
      },
      {
       "label": "Integration Type",
       "html": "<p>A mix of file, event and query [U]</p>"
      },
      {
       "label": "Data Exchanged",
       "html": "<ul><li><strong>Outbound</strong>: coverage applications; reported changes to name, sex or birth date.</li><li><strong>Inbound</strong>: coverage status; identity matches; death notifications.</li></ul>"
      },
      {
       "label": "Integration Pattern",
       "html": "<p>Asynchronous. Health data is Protected C, and cross-ministry traffic goes through the exchange.</p>"
      },
      {
       "label": "Authentication",
       "html": "<p>As the agreement specifies [U].</p>"
      },
      {
       "label": "Error Handling",
       "html": "<p>Pending coverage appears as a work item (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-029\">FR-029</a>).</p>"
      },
      {
       "label": "SLA",
       "html": "<p>Not stated.</p>"
      },
      {
       "label": "Owner",
       "html": "<p>Ministry of Health and Health Insurance BC; the ministry business owner named in the inventory.</p>"
      },
      {
       "label": "Classification",
       "html": "<p>Protected C</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>Health coverage depends on assistance status (TA §C.13.3).</p>"
      }
     ]
    },
    {
     "id": "INT-009",
     "anchor": "int-009",
     "title": "Pacific Blue Cross (delegated decision-maker)",
     "priority": "Must",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "Exchange requests and decisions for the health supplement lines Pacific Blue Cross decides, and receive the outcomes that use up ministry replacement intervals.",
     "fields": [
      {
       "label": "Purpose",
       "html": "<p>Exchange requests and decisions for the health supplement lines <a class=\"g\" href=\"%BASE%/glossary#pbc-clbc\">Pacific Blue Cross</a> decides, and receive the outcomes that use up ministry replacement intervals.</p>"
      },
      {
       "label": "Integration Type",
       "html": "<p>Batch, API or both [U]</p>"
      },
      {
       "label": "Data Exchanged",
       "html": "<ul><li><strong>Inbound</strong>: first decisions, recorded as evidence with their source; outcomes that use up ministry replacement intervals.</li><li><strong>Outbound</strong>: eligibility confirmations; the ministry's rules and intervals as the administrator applies them.</li></ul>"
      },
      {
       "label": "Integration Pattern",
       "html": "<p>Asynchronous. External decisions are taken in under <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-036\">FR-036</a>.</p>"
      },
      {
       "label": "Authentication",
       "html": "<p>As the contract specifies.</p>"
      },
      {
       "label": "Error Handling",
       "html": "<p>A missing return is detected by checking the record of used intervals.</p>"
      },
      {
       "label": "SLA",
       "html": "<p>The contract obliges the administrator to send outcomes back, and to make its records disclosable and severable. Both are needed because Reconsideration must review decisions it did not make.</p>"
      },
      {
       "label": "Owner",
       "html": "<p>Pacific Blue Cross; the ministry's health supplement business owner.</p>"
      },
      {
       "label": "Classification",
       "html": "<p>Protected C</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>Policy never requires these outcomes to be sent back, so the ministry's clocks run where only the administrator can see them <span class=\"cite\">MAP-C2</span>.</p>"
      }
     ]
    },
    {
     "id": "INT-010",
     "anchor": "int-010",
     "title": "Community Living British Columbia",
     "priority": "Must",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "Receive CLBC's decisions and appeal outcomes for the entitlement it decides and reviews, and issue payment on them.",
     "fields": [
      {
       "label": "Purpose",
       "html": "<p>Receive CLBC's decisions and appeal outcomes for the entitlement it decides and reviews, and issue payment on them.</p>"
      },
      {
       "label": "Integration Type",
       "html": "<p>Batch, portal or both [U]</p>"
      },
      {
       "label": "Data Exchanged",
       "html": "<ul><li><strong>Inbound</strong>: eligibility decisions, appeal outcomes and prescribed-class verifications.</li><li><strong>Outbound</strong>: payment status.</li></ul>"
      },
      {
       "label": "Integration Pattern",
       "html": "<p>Asynchronous. The record shows that the ministry keeps only the power to issue payment (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-036\">FR-036</a>).</p>"
      },
      {
       "label": "Authentication",
       "html": "<p>As the agreement specifies [U].</p>"
      },
      {
       "label": "Error Handling",
       "html": "<p>No payment is made without a recognised decision.</p>"
      },
      {
       "label": "SLA",
       "html": "<p>Not stated. The CLBC appeal runs on no clock the ministry can see.</p>"
      },
      {
       "label": "Owner",
       "html": "<p>CLBC; the ministry business owner named in the inventory.</p>"
      },
      {
       "label": "Classification",
       "html": "<p>Protected C</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>The ministry pays on a decision it neither made nor can review (PRIN <a class=\"rid\" href=\"%BASE%/parameters#n17\">N17</a> v3.5).</p>"
      }
     ]
    },
    {
     "id": "INT-011",
     "anchor": "int-011",
     "title": "Employment and Assistance Appeal Tribunal",
     "priority": "Must",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "Send appeal records;",
     "fields": [
      {
       "label": "Purpose",
       "html": "<p>Send appeal records; receive notices of appeal, hearing details, the outcome of each appeal and the panel's decision.</p>"
      },
      {
       "label": "Integration Type",
       "html": "<p>Records go out and decisions come back. The exchange mechanism is unconfirmed [U].</p>"
      },
      {
       "label": "Data Exchanged",
       "html": "<ul><li><strong>Outbound</strong>: the severed appeal record, sent to the tribunal and, through it, to the appellant.</li><li><strong>Inbound</strong>: notice of appeal (<a class=\"g\" href=\"%BASE%/glossary#tribunal\">EAAT001</a>), hearing schedule, how the appeal ended, and whether the panel confirmed or rescinded.</li></ul>"
      },
      {
       "label": "Integration Pattern",
       "html": "<p>Asynchronous. The tribunal is an external party, not a user of the system.</p>"
      },
      {
       "label": "Authentication",
       "html": "<p>As agreed. Legal counsel is still to confirm the legal basis for disclosure.</p>"
      },
      {
       "label": "Error Handling",
       "html": "<p>The record-supply clock and the hearing clock are registered (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-061\">FR-061</a>), so a missed deadline is detected.</p>"
      },
      {
       "label": "SLA",
       "html": "<p>The record is supplied within the period the tribunal sets. The hearing is held within the tribunal's clock.</p>"
      },
      {
       "label": "Owner",
       "html": "<p>The tribunal; <a class=\"g\" href=\"%BASE%/glossary#rafu\">Reconsideration and Administrative Fairness Unit</a>.</p>"
      },
      {
       "label": "Classification",
       "html": "<p>Protected C</p>"
      },
      {
       "label": "Rationale",
       "html": "<p><a class=\"g\" href=\"%BASE%/glossary#legal-time-limit\">Statutory clocks</a> depend on this exchange (TA §C.8.2). Policy now confirms which tribunal it is (NOTE-006).</p>"
      }
     ]
    },
    {
     "id": "INT-012",
     "anchor": "int-012",
     "title": "BCANDS, Indigenous Services Canada and First Nations that run assistance",
     "priority": "Must",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "Each side recognises the other's disability designations.",
     "fields": [
      {
       "label": "Purpose",
       "html": "<p>Each side recognises the other's disability designations. The ministry verifies on-reserve designations. For people living on reserve or on <a class=\"g\" href=\"%BASE%/glossary#modern-treaty\">Modern Treaty land</a>, the system records where they are sent and the evidence for any exception.</p>"
      },
      {
       "label": "Integration Type",
       "html": "<p>Request and response through Band Social Development Workers and the deciding body [U]</p>"
      },
      {
       "label": "Data Exchanged",
       "html": "<ul><li><strong>Outbound</strong>: verification of ministry designations, within the registered clock.</li><li><strong>Inbound</strong>: designations made in the other jurisdiction, recorded with how current they are; First Nation confirmations.</li></ul>"
      },
      {
       "label": "Integration Pattern",
       "html": "<p>Asynchronous. Where a body acts under its own jurisdiction, it is recorded in the <a class=\"g\" href=\"%BASE%/glossary#non-crown\">non-Crown</a> branch of the registry (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-085\">FR-085</a>).</p>"
      },
      {
       "label": "Authentication",
       "html": "<p>As the agreement specifies.</p>"
      },
      {
       "label": "Error Handling",
       "html": "<p>Today neither side tells the other when a designation changes. The record therefore says \"recognised as at [date], not confirmed since\".</p>"
      },
      {
       "label": "SLA",
       "html": "<p>The ministry's verification clock, as registered.</p>"
      },
      {
       "label": "Owner",
       "html": "<p>BCANDS, ISC and First Nations; the ministry's Indigenous relations function.</p>"
      },
      {
       "label": "Classification",
       "html": "<p>Protected B/C</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>Mutual recognition took effect on 2026-07-13 and is new (OBLG §4.4); DRV-06.</p>"
      }
     ]
    },
    {
     "id": "INT-013",
     "anchor": "int-013",
     "title": "Ministry of Children and Family Development and delegated agencies",
     "priority": "Must",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "Report child protection concerns, respond to disclosure requests under section 96 of the CFCSA, run screening for the Child in the Home of a Relative program, and work with delegated agencies.",
     "fields": [
      {
       "label": "Purpose",
       "html": "<p>Report child protection concerns, respond to disclosure requests under section 96 of the <a class=\"g\" href=\"%BASE%/glossary#cfcsa\">CFCSA</a>, run screening for the <a class=\"g\" href=\"%BASE%/glossary#cihr\">Child in the Home of a Relative</a> program, and work with <a class=\"g\" href=\"%BASE%/glossary#delegated-agency\">delegated agencies</a>. The close ties between the two ministries continue until child protection is captured (<a class=\"g\" href=\"%BASE%/glossary#module\">M9</a>).</p>"
      },
      {
       "label": "Integration Type",
       "html": "<p>A mix of referral, request and response, and partner access [U]</p>"
      },
      {
       "label": "Data Exchanged",
       "html": "<ul><li><strong>Outbound</strong>: reports and referrals; information disclosed in writing under section 96.</li><li><strong>Inbound</strong>: screening results; requests; submissions from delegated agencies.</li></ul>"
      },
      {
       "label": "Integration Pattern",
       "html": "<p>Cross-ministry traffic goes through the <a class=\"g\" href=\"%BASE%/glossary#secure-data-exchange\">Secure Data Exchange</a> (<a class=\"rid\" href=\"%BASE%/requirements/integrations#int-022\">INT-022</a>). Delegated-agency access is listed first, because external users with direct access to the <a class=\"g\" href=\"%BASE%/glossary#old-system\">legacy system</a> are the riskiest group not yet listed (TA §C.12.1).</p>"
      },
      {
       "label": "Authentication",
       "html": "<p>Through the exchange and the agreement registry.</p>"
      },
      {
       "label": "Error Handling",
       "html": "<p>If a referral cannot be sent electronically, it goes by a recorded manual route. It is never dropped.</p>"
      },
      {
       "label": "SLA",
       "html": "<p>The duty to report is immediate. The screening mailbox is checked daily today.</p>"
      },
      {
       "label": "Owner",
       "html": "<p>MCFD and the delegated agencies; the ministry business owner named in the inventory.</p>"
      },
      {
       "label": "Classification",
       "html": "<p>Protected C</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>Child safety depends on this exchange, which makes it the most critical (TA §C.13.3); DRV-08.</p>"
      }
     ]
    },
    {
     "id": "INT-014",
     "anchor": "int-014",
     "title": "Ministry of Public Safety and Solicitor General",
     "priority": "Must",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "Confirm outstanding arrest warrants for applicants and recipients who have consented.",
     "fields": [
      {
       "label": "Purpose",
       "html": "<p>Confirm outstanding arrest warrants for applicants and recipients who have consented.</p>"
      },
      {
       "label": "Integration Type",
       "html": "<p>Request and response [U]</p>"
      },
      {
       "label": "Data Exchanged",
       "html": "<ul><li><strong>Outbound</strong>: confirmation requests with the consent reference.</li><li><strong>Inbound</strong>: confirmation results.</li></ul>"
      },
      {
       "label": "Integration Pattern",
       "html": "<p>Asynchronous, through the exchange.</p>"
      },
      {
       "label": "Authentication",
       "html": "<p>Through the exchange.</p>"
      },
      {
       "label": "Error Handling",
       "html": "<p>An unconfirmed warrant flag cannot drive a determination (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-016\">FR-016</a>).</p>"
      },
      {
       "label": "SLA",
       "html": "<p>Not stated.</p>"
      },
      {
       "label": "Owner",
       "html": "<p>PSSG; the ministry business owner named in the inventory.</p>"
      },
      {
       "label": "Classification",
       "html": "<p>Protected B/C</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>Policy recognises only a confirmed warrant (OB-EL-36).</p>"
      }
     ]
    },
    {
     "id": "INT-015",
     "anchor": "int-015",
     "title": "Third-party verification sources",
     "priority": "Must",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "Run the mandatory and discretionary third-party checks where valid consent exists.",
     "fields": [
      {
       "label": "Purpose",
       "html": "<p>Run the mandatory and discretionary third-party checks where valid consent exists. These cover consumer credit, vehicle and driver records, land title and personal property registries, property assessment, student financial assistance, and financial institution queries.</p>"
      },
      {
       "label": "Integration Type",
       "html": "<p>Query, automated where the source allows [U]</p>"
      },
      {
       "label": "Data Exchanged",
       "html": "<ul><li><strong>Outbound</strong>: queries covered by consent.</li><li><strong>Inbound</strong>: results, including \"no record found\", recorded as evidence with the source named.</li></ul>"
      },
      {
       "label": "Integration Pattern",
       "html": "<p>Asynchronous, with work items. The new system does not use screen-scraping robots, except as a dated, recorded exception.</p>"
      },
      {
       "label": "Authentication",
       "html": "<p>As each source requires.</p>"
      },
      {
       "label": "Error Handling",
       "html": "<p>A failed check is retried or deferred as policy says. The system never assumes a result.</p>"
      },
      {
       "label": "SLA",
       "html": "<p>Not stated.</p>"
      },
      {
       "label": "Owner",
       "html": "<p>Each source organisation; the ministry business owner named in the inventory.</p>"
      },
      {
       "label": "Classification",
       "html": "<p>Protected B</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>These checks are mandatory at application, eligibility review and compliance review (OB-EL-04).</p>"
      }
     ]
    },
    {
     "id": "INT-016",
     "anchor": "int-016",
     "title": "Vital statistics",
     "priority": "Should",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "Receive births, deaths and name changes as events.",
     "fields": [
      {
       "label": "Purpose",
       "html": "<p>Receive births, deaths and name changes as events.</p>"
      },
      {
       "label": "Integration Type",
       "html": "<p>Event or batch [U]</p>"
      },
      {
       "label": "Data Exchanged",
       "html": "<ul><li><strong>Inbound</strong>: births, deaths and name changes.</li></ul>"
      },
      {
       "label": "Integration Pattern",
       "html": "<p>Asynchronous. A death stops future payments and starts the related work.</p>"
      },
      {
       "label": "Authentication",
       "html": "<p>As the agreement specifies [U].</p>"
      },
      {
       "label": "Error Handling",
       "html": "<p>Matching runs through the <a class=\"g\" href=\"%BASE%/glossary#client-index\">client index</a> (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-028\">FR-028</a>). A person decides any uncertain match.</p>"
      },
      {
       "label": "SLA",
       "html": "<p>Not stated.</p>"
      },
      {
       "label": "Owner",
       "html": "<p>Provincial vital statistics service; the ministry business owner named in the inventory.</p>"
      },
      {
       "label": "Classification",
       "html": "<p>Protected B</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>Death notices prevent overpayment, and births change entitlement (TA §C.13.3).</p>"
      }
     ]
    },
    {
     "id": "INT-017",
     "anchor": "int-017",
     "title": "Public Guardian and Trustee",
     "priority": "Should",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "Exchange Senior's Supplement information, and handle trustee arrangements where the Public Guardian and Trustee receives or manages a client's payments.",
     "fields": [
      {
       "label": "Purpose",
       "html": "<p>Exchange Senior's Supplement information, and handle trustee arrangements where the Public Guardian and Trustee receives or manages a client's payments.</p>"
      },
      {
       "label": "Integration Type",
       "html": "<p>Batch file transfer (daily today)</p>"
      },
      {
       "label": "Data Exchanged",
       "html": "<ul><li><strong>Both directions</strong>: supplement eligibility and payment data; trustee roles.</li></ul>"
      },
      {
       "label": "Integration Pattern",
       "html": "<p>Asynchronous. The trustee is recorded as a payee role on <a class=\"g\" href=\"%BASE%/glossary#payment-instruction\">payment instructions</a> (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-042\">FR-042</a>).</p>"
      },
      {
       "label": "Authentication",
       "html": "<p>SFTP credentials.</p>"
      },
      {
       "label": "Error Handling",
       "html": "<p>A failed file raises an alarm.</p>"
      },
      {
       "label": "SLA",
       "html": "<p>Daily.</p>"
      },
      {
       "label": "Owner",
       "html": "<p>PGT; the ministry business owner named in the inventory.</p>"
      },
      {
       "label": "Classification",
       "html": "<p>Protected B</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>This integration is in the application inventory (APP §1.8).</p>"
      }
     ]
    },
    {
     "id": "INT-018",
     "anchor": "int-018",
     "title": "Transit authorities",
     "priority": "Should",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "Issue, renew, replace and cancel transit passes for eligible recipients.",
     "fields": [
      {
       "label": "Purpose",
       "html": "<p>Issue, renew, replace and cancel transit passes for eligible recipients.</p>"
      },
      {
       "label": "Integration Type",
       "html": "<p>Batch file transfer in set time windows</p>"
      },
      {
       "label": "Data Exchanged",
       "html": "<ul><li><strong>Outbound</strong>: pass applications, changes and cancellations.</li><li><strong>Inbound</strong>: confirmations that passes were issued.</li></ul>"
      },
      {
       "label": "Integration Pattern",
       "html": "<p>Asynchronous.</p>"
      },
      {
       "label": "Authentication",
       "html": "<p>SFTP credentials.</p>"
      },
      {
       "label": "Error Handling",
       "html": "<p>A rejected record becomes a work item.</p>"
      },
      {
       "label": "SLA",
       "html": "<p>The transit authorities' time windows.</p>"
      },
      {
       "label": "Owner",
       "html": "<p>BC Transit and TransLink; the ministry business owner for the transportation supplement.</p>"
      },
      {
       "label": "Classification",
       "html": "<p>Protected B</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>There are 7 named interfaces today (APP §4.2), and the bus pass is a registered entitlement.</p>"
      }
     ]
    },
    {
     "id": "INT-019",
     "anchor": "int-019",
     "title": "Collections",
     "priority": "Must",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "Refer debts to a collections service or agent, and receive recoveries.",
     "fields": [
      {
       "label": "Purpose",
       "html": "<p>Refer debts to a collections service or agent, and receive recoveries.</p>"
      },
      {
       "label": "Integration Type",
       "html": "<p>Referral by event [U]</p>"
      },
      {
       "label": "Data Exchanged",
       "html": "<ul><li><strong>Outbound</strong>: referrals and recalls.</li><li><strong>Inbound</strong>: recoveries.</li></ul>"
      },
      {
       "label": "Integration Pattern",
       "html": "<p>Overpayment &amp; Recovery keeps ownership of the debt. A referral is an event, not a data export, and can be <strong>recalled in one operation</strong> (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-053\">FR-053</a>).</p>"
      },
      {
       "label": "Authentication",
       "html": "<p>As the agreement specifies.</p>"
      },
      {
       "label": "Error Handling",
       "html": "<p>A failed recall raises an alarm at once.</p>"
      },
      {
       "label": "SLA",
       "html": "<p>Not stated.</p>"
      },
      {
       "label": "Owner",
       "html": "<p>The collections service or agent; the ministry's Overpayment &amp; Recovery business owner.</p>"
      },
      {
       "label": "Classification",
       "html": "<p>Protected B</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>This follows the architecture's rule for collections (TA §C.7.4).</p>"
      }
     ]
    },
    {
     "id": "INT-020",
     "anchor": "int-020",
     "title": "Provider contract management and provider portal",
     "priority": "Should",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "Exchange provider records, contracts, orders, invoices and payment status with the ministry's provider contract system and provider portal.",
     "fields": [
      {
       "label": "Purpose",
       "html": "<p>Exchange provider records, contracts, orders, invoices and payment status with the ministry's provider contract system and provider portal.</p>"
      },
      {
       "label": "Integration Type",
       "html": "<p>REST API with OAuth token exchange</p>"
      },
      {
       "label": "Data Exchanged",
       "html": "<ul><li><strong>Both directions</strong>: provider recognition, orders, invoices and payment status.</li></ul>"
      },
      {
       "label": "Integration Pattern",
       "html": "<p>The current provider contract system (<a class=\"g\" href=\"%BASE%/glossary#pcms\">PCMS</a>) is recent. It is to be assessed for keeping rather than replacing (APP §2). The integration goes through the <a class=\"g\" href=\"%BASE%/glossary#interface\">published contract</a>.</p>"
      },
      {
       "label": "Authentication",
       "html": "<p>OAuth through the provincial identity service.</p>"
      },
      {
       "label": "Error Handling",
       "html": "<p>An invoice that does not match becomes a work item.</p>"
      },
      {
       "label": "SLA",
       "html": "<p>Not stated.</p>"
      },
      {
       "label": "Owner",
       "html": "<p>The provider contract management service owner.</p>"
      },
      {
       "label": "Classification",
       "html": "<p>Protected B</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>Provider &amp; Outcome Management already has a system in place (APP §12).</p>"
      }
     ]
    },
    {
     "id": "INT-021",
     "anchor": "int-021",
     "title": "Employment services (WorkBC)",
     "priority": "Should",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "Exchange employment-service referrals, plans and messages about client issues.",
     "fields": [
      {
       "label": "Purpose",
       "html": "<p>Exchange employment-service referrals, plans and messages about client issues.</p>"
      },
      {
       "label": "Integration Type",
       "html": "<p>API and exchange of work items [U]</p>"
      },
      {
       "label": "Data Exchanged",
       "html": "<ul><li><strong>Both directions</strong>: referrals, plan status and requests to communicate.</li></ul>"
      },
      {
       "label": "Integration Pattern",
       "html": "<p>Asynchronous.</p>"
      },
      {
       "label": "Authentication",
       "html": "<p>As agreed.</p>"
      },
      {
       "label": "Error Handling",
       "html": "<p>A failed message becomes a work item.</p>"
      },
      {
       "label": "SLA",
       "html": "<p>Not stated.</p>"
      },
      {
       "label": "Owner",
       "html": "<p>The employment services program; the ministry business owner named in the inventory.</p>"
      },
      {
       "label": "Classification",
       "html": "<p>Protected B</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>Employment services are in the architecture's scope. How deep these requirements go follows <a class=\"rid\" href=\"%BASE%/requirements/business#br-014\">BR-014</a>.</p>"
      }
     ]
    },
    {
     "id": "INT-022",
     "anchor": "int-022",
     "title": "Secure Data Exchange",
     "priority": "Must",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "Carry all exchange with other ministries.",
     "fields": [
      {
       "label": "Purpose",
       "html": "<p>Carry all exchange with other ministries. The exchange provides secure transport and access control. This system adds the evidence of what was exchanged.</p>"
      },
      {
       "label": "Integration Type",
       "html": "<p>API gateway</p>"
      },
      {
       "label": "Data Exchanged",
       "html": "<ul><li><strong>Both directions</strong>: every cross-ministry request and response, each carrying a token limited to its purpose and an agreement identifier.</li></ul>"
      },
      {
       "label": "Integration Pattern",
       "html": "<p>Gateway configuration is generated only from the agreement registry (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-085\">FR-085</a>). Evidence tier <a class=\"g\" href=\"%BASE%/glossary#evidence-tier\">E1</a> is in place before the first production exchange (<a class=\"rid\" href=\"%BASE%/requirements/quality#nfr-sec-010\">NFR-SEC-010</a>).</p>"
      },
      {
       "label": "Authentication",
       "html": "<p>Mutual TLS and delegated tokens.</p>"
      },
      {
       "label": "Error Handling",
       "html": "<p>When the exchange is down, determinations proceed on the evidence held, where policy permits, and are flagged for later verification (<a class=\"rid\" href=\"%BASE%/requirements/quality#nfr-a-008\">NFR-A-008</a>).</p>"
      },
      {
       "label": "SLA",
       "html": "<p>No availability target has been committed. It must be obtained in writing (DEP-06).</p>"
      },
      {
       "label": "Owner",
       "html": "<p>The provincial exchange programme; ministry CIO.</p>"
      },
      {
       "label": "Classification",
       "html": "<p>Up to Protected C in transit</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>This is commitment 1 (TA §A.3).</p>"
      }
     ]
    },
    {
     "id": "INT-023",
     "anchor": "int-023",
     "title": "Legacy platforms while old and new run side by side",
     "priority": "Must",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "Serve the published contract from the legacy platforms while capture proceeds;",
     "fields": [
      {
       "label": "Purpose",
       "html": "<p>Serve the published contract from the legacy platforms while capture proceeds; write data back to legacy for captured <a class=\"g\" href=\"%BASE%/glossary#client-group\">cohorts</a>; feed the <a class=\"g\" href=\"%BASE%/glossary#shadow\">shadow comparison</a>.</p>"
      },
      {
       "label": "Integration Type",
       "html": "<p><a class=\"g\" href=\"%BASE%/glossary#translation-layer\">Anti-corruption layer</a> (facade, adapter and translator), runtime events, transactional <a class=\"g\" href=\"%BASE%/glossary#event\">outbox</a>, change-data capture</p>"
      },
      {
       "label": "Data Exchanged",
       "html": "<ul><li><strong>From the legacy platforms</strong>: events and read models for cohorts not yet captured; the inputs each legacy decision used (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-095\">FR-095</a>).</li><li><strong>To the legacy platforms</strong>: <a class=\"g\" href=\"%BASE%/glossary#write-back\">write-back</a> for captured cohorts, using insert and update operations only (<a class=\"rid\" href=\"%BASE%/requirements/data#dr-014\">DR-014</a>).</li></ul>"
      },
      {
       "label": "Integration Pattern",
       "html": "<p>The layer holds no business rules and is set up to be retired. <a class=\"g\" href=\"%BASE%/glossary#old-system\">MIS</a> is not a passive store: it holds payment issuance, debt and time limits, and it is the master copy when income data conflicts (APP §2). Both the coexistence design and the legacy side of the shadow comparison must therefore include MIS and every other legacy system that runs program logic (APP §7.1).</p>"
      },
      {
       "label": "Authentication",
       "html": "<p>Dedicated integration identities. Write-back uses its own identity, so the system can recognise its own writes and stop them looping back.</p>"
      },
      {
       "label": "Error Handling",
       "html": "<p>A late legacy change to a captured record goes to a queue for a person to reconcile (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-098\">FR-098</a>).</p>"
      },
      {
       "label": "SLA",
       "html": "<p>Sized from the measured point at which the legacy platform saturates (<a class=\"rid\" href=\"%BASE%/requirements/quality#nfr-p-001\">NFR-P-001</a>).</p>"
      },
      {
       "label": "Owner",
       "html": "<p>The coexistence lead; the legacy platform's configuration authority, whose capacity is itself an open dependency (DEP-03).</p>"
      },
      {
       "label": "Classification",
       "html": "<p>Protected C</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>Replacing the legacy platforms step by step is impossible without this (commitment 3). A comparison against only part of the legacy calculation is not a real check (TA §C.2.7).</p>"
      }
     ]
    },
    {
     "id": "INT-024",
     "anchor": "int-024",
     "title": "Recipients entitled to disclosure by law",
     "priority": "Must",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "Disclose information on request to recipients entitled to it by statute or policy.",
     "fields": [
      {
       "label": "Purpose",
       "html": "<p>Disclose information on request to recipients entitled to it by statute or policy. These are the <a class=\"g\" href=\"%BASE%/glossary#fmep\">maintenance enforcement program</a>, coroners, police where authorised, and elected members acting for constituents with a certificate of authority.</p>"
      },
      {
       "label": "Integration Type",
       "html": "<p>Request and response, mostly manual [U]</p>"
      },
      {
       "label": "Data Exchanged",
       "html": "<ul><li><strong>Outbound</strong>: only the permitted information, with severing and use limits applied. Personal correspondence may not go to the maintenance program without consent (<a class=\"rid\" href=\"%BASE%/requirements/functional#fr-080\">FR-080</a>).</li></ul>"
      },
      {
       "label": "Integration Pattern",
       "html": "<p>Each disclosure is recorded under <a class=\"rid\" href=\"%BASE%/requirements/functional#fr-077\">FR-077</a>.</p>"
      },
      {
       "label": "Authentication",
       "html": "<p>The requester's identity and authority are confirmed first.</p>"
      },
      {
       "label": "Error Handling",
       "html": "<p>A request without the required authority is refused and recorded.</p>"
      },
      {
       "label": "SLA",
       "html": "<p>Not stated.</p>"
      },
      {
       "label": "Owner",
       "html": "<p>The access and privacy office.</p>"
      },
      {
       "label": "Classification",
       "html": "<p>Protected B/C</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>These disclosure duties come from obligations OB-IN-38, OB-IN-40 and OB-IN-41.</p>"
      }
     ]
    },
    {
     "id": "INT-025",
     "anchor": "int-025",
     "title": "Sanctioned provincial payment service",
     "priority": "Must",
     "priorityNote": "",
     "module": null,
     "moduleText": "",
     "complexity": null,
     "lead": "Send card payments and some electronic payments through the province's approved payment service, which posts to the corporate financial system.",
     "fields": [
      {
       "label": "Purpose",
       "html": "<p>Send card payments and some electronic payments through the province's approved payment service, which posts to the corporate financial system.</p>"
      },
      {
       "label": "Integration Type",
       "html": "<p>API and batch</p>"
      },
      {
       "label": "Data Exchanged",
       "html": "<ul><li><strong>Outbound</strong>: payment instructions.</li><li><strong>Inbound</strong>: tokens and settlement references. <strong>No cardholder data</strong> enters ministry systems.</li></ul>"
      },
      {
       "label": "Integration Pattern",
       "html": "<p>One of the Issuance Service's payment channels. It does not bypass the Issuance Service.</p>"
      },
      {
       "label": "Authentication",
       "html": "<p>As the service requires.</p>"
      },
      {
       "label": "Error Handling",
       "html": "<p>Differences in posting times are reconciled.</p>"
      },
      {
       "label": "SLA",
       "html": "<p>The service's stated levels.</p>"
      },
      {
       "label": "Owner",
       "html": "<p>The provincial payment service; the Executive Financial Officer.</p>"
      },
      {
       "label": "Classification",
       "html": "<p>Tokenised</p>"
      },
      {
       "label": "Rationale",
       "html": "<p>This keeps the platform out of <a class=\"g\" href=\"%BASE%/glossary#pci\">PCI-DSS</a> scope (TA §C.6.7).</p>"
      }
     ]
    }
   ]
  }
 ]
};
