// Generated by scripts/build-requirements.py from the requirements specification. Do not edit by hand.
export default {
 "version": "1.6",
 "categories": [
  {
   "key": "business",
   "label": "Business",
   "count": 25,
   "groups": 1,
   "priorities": {
    "Must": 24,
    "Should": 1
   }
  },
  {
   "key": "functional",
   "label": "Functional",
   "count": 481,
   "groups": 34,
   "priorities": {
    "Must": 444,
    "Should": 34,
    "Won't": 3
   }
  },
  {
   "key": "quality",
   "label": "Quality",
   "count": 64,
   "groups": 8,
   "priorities": {
    "Must": 60,
    "Should": 4
   }
  },
  {
   "key": "integrations",
   "label": "Integrations",
   "count": 42,
   "groups": 1,
   "priorities": {
    "Must": 28,
    "Should": 14
   }
  },
  {
   "key": "data",
   "label": "Data",
   "count": 31,
   "groups": 3,
   "priorities": {
    "Must": 30,
    "Should": 1
   }
  }
 ],
 "total": 643,
 "modules": [
  {
   "module": 0,
   "count": 115
  },
  {
   "module": 1,
   "count": 10
  },
  {
   "module": 2,
   "count": 4
  },
  {
   "module": 3,
   "count": 9
  },
  {
   "module": 4,
   "count": 8
  },
  {
   "module": 5,
   "count": 9
  },
  {
   "module": 6,
   "count": 14
  },
  {
   "module": 7,
   "count": 6
  },
  {
   "module": 8,
   "count": 18
  },
  {
   "module": 9,
   "count": 284
  }
 ],
 "obligations": 270,
 "cfdProvisions": 3689,
 "cfdMet": 2001,
 "cfdRequirements": 378,
 "parameters": 21,
 "conflicts": 13,
 "openConflicts": 6
};
