// Generated by scripts/build-requirements.py from the requirements specification. Do not edit by hand.
export default {
 "version": "1.1",
 "categories": [
  {
   "key": "business",
   "label": "Business",
   "count": 14,
   "groups": 1,
   "priorities": {
    "Must": 14
   }
  },
  {
   "key": "functional",
   "label": "Functional",
   "count": 99,
   "groups": 16,
   "priorities": {
    "Must": 91,
    "Should": 5,
    "Won't": 3
   }
  },
  {
   "key": "quality",
   "label": "Quality",
   "count": 56,
   "groups": 8,
   "priorities": {
    "Must": 53,
    "Should": 3
   }
  },
  {
   "key": "integrations",
   "label": "Integrations",
   "count": 25,
   "groups": 1,
   "priorities": {
    "Must": 19,
    "Should": 6
   }
  },
  {
   "key": "data",
   "label": "Data",
   "count": 19,
   "groups": 3,
   "priorities": {
    "Must": 17,
    "Should": 2
   }
  }
 ],
 "total": 213,
 "modules": [
  {
   "module": 0,
   "count": 20
  },
  {
   "module": 1,
   "count": 10
  },
  {
   "module": 2,
   "count": 4
  },
  {
   "module": 3,
   "count": 9
  },
  {
   "module": 4,
   "count": 8
  },
  {
   "module": 5,
   "count": 9
  },
  {
   "module": 6,
   "count": 11
  },
  {
   "module": 7,
   "count": 6
  },
  {
   "module": 8,
   "count": 18
  },
  {
   "module": 9,
   "count": 0
  }
 ],
 "obligations": 270,
 "parameters": 21,
 "conflicts": 8,
 "openConflicts": 2
};
