// Copy lock. Pulls every piece of reader-facing text out of the built site and
// compares it with copy.lock.txt, so a refactor cannot silently change wording.
//
//   node scripts/copy-lock.js check    exit 1 and print a diff if copy changed
//   node scripts/copy-lock.js update   rewrite copy.lock.txt from the build
//
// Run `vite build` first. Two sources are captured:
//   1. Rendered pages: title, meta description, visible text and accessible
//      names, in page order.
//   2. From the .svelte sources: string literals in <script> blocks, and text in
//      markup. This covers text that only appears after interaction (context map
//      panels, {#if} branches). It is a sorted set, so moving text between files
//      does not trip it.

import { readFileSync, writeFileSync, readdirSync, statSync, existsSync, mkdtempSync } from 'node:fs';
import { join, relative, dirname } from 'node:path';
import { tmpdir } from 'node:os';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const lockPath = join(root, 'copy.lock.txt');
const mode = process.argv[2];

function walk(dir, ext) {
  return readdirSync(dir)
    .flatMap((name) => {
      const p = join(dir, name);
      return statSync(p).isDirectory() ? walk(p, ext) : p.endsWith(ext) ? [p] : [];
    })
    .sort();
}

const named = { amp: '&', lt: '<', gt: '>', quot: '"', apos: "'", nbsp: ' ', rsquo: '’', lsquo: '‘', rdquo: '”', ldquo: '“', mdash: '—', ndash: '–', hellip: '…' };
function decode(s) {
  return s.replace(/&(#x[0-9a-f]+|#\d+|[a-z]+);/gi, (m, e) => {
    if (e[0] === '#') return String.fromCodePoint(e[1] === 'x' || e[1] === 'X' ? parseInt(e.slice(2), 16) : +e.slice(1));
    return named[e.toLowerCase()] ?? m;
  });
}

const tidy = (s) => decode(s).replace(/\s+/g, ' ').trim();

const BLOCK = /<\/?(p|li|ul|ol|h[1-6]|div|section|article|header|footer|nav|main|figure|figcaption|details|summary|table|tr|td|th|dt|dd|dl|blockquote|button|label|legend|fieldset|output|br|hr|text|title|option)\b[^>]*>/gi;
const IS_BLOCK = new RegExp(BLOCK.source, 'i');
const BREAK = '\u0000';

function pageText(html) {
  const lines = [];
  const title = html.match(/<title>([\s\S]*?)<\/title>/i);
  if (title) lines.push(`title: ${tidy(title[1])}`);
  const desc = html.match(/<meta\s+name="description"\s+content="([^"]*)"/i);
  if (desc) lines.push(`description: ${tidy(desc[1])}`);

  let body = (html.match(/<body[^>]*>([\s\S]*)<\/body>/i) ?? ['', ''])[1]
    .replace(/<script[\s\S]*?<\/script>/gi, '')
    .replace(/<style[\s\S]*?<\/style>/gi, '')
    .replace(/<!--[\s\S]*?-->/g, '');

  // Break only at block boundaries, never at source line breaks, so reflowing a
  // paragraph in the .svelte file is not a copy change. Accessible names are
  // copy too; each gets its own line.
  body = body.replace(/<[a-z][^>]*>/gi, (tag) => {
    const attrs = [...tag.matchAll(/\s(aria-label|alt|title|placeholder)="([^"]*)"/gi)];
    const out = attrs.map(([, k, v]) => `${BREAK}[${k}] ${v}${BREAK}`).join('');
    return IS_BLOCK.test(tag) ? `${out}${BREAK}` : out;
  });
  body = body.replace(BLOCK, BREAK).replace(/<[^>]+>/g, '');

  for (const line of body.split(BREAK)) {
    const t = tidy(line);
    if (t) lines.push(t);
  }
  return lines;
}

// Minimal tokenizer: skips comments, collects string literals.
function scriptStrings(src) {
  const out = [];
  let i = 0;
  while (i < src.length) {
    const c = src[i];
    if (c === '/' && src[i + 1] === '/') { i = src.indexOf('\n', i); if (i < 0) break; continue; }
    if (c === '/' && src[i + 1] === '*') { i = src.indexOf('*/', i + 2); if (i < 0) break; i += 2; continue; }
    if (c === "'" || c === '"' || c === '`') {
      let j = i + 1, s = '';
      while (j < src.length && src[j] !== c) {
        if (src[j] === '\\') { s += src[j + 1]; j += 2; } else s += src[j++];
      }
      out.push(s);
      i = j + 1;
      continue;
    }
    i++;
  }
  return out;
}

// Text fragments in component markup, split at tags and {expressions}.
function markupText(src) {
  let m = src
    .replace(/<script[\s\S]*?<\/script>/gi, '')
    .replace(/<style[\s\S]*?<\/style>/gi, '')
    .replace(/<!--[\s\S]*?-->/g, '');
  const out = [...m.matchAll(/\s(?:aria-label|alt|title|placeholder|content|summary)="([^"{]*)"/gi)].map((x) => x[1]);
  m = m.replace(/<[^>]*>/g, '\u0000');
  for (let prev; prev !== m; ) (prev = m), (m = m.replace(/\{[^{}]*\}/g, '\u0000'));
  return out.concat(m.split('\u0000'));
}

function snapshot() {
  const build = join(root, 'build');
  if (!existsSync(build)) {
    console.error('No build/ directory. Run `npm run build` first.');
    process.exit(2);
  }
  const parts = ['# Copy lock. Generated by scripts/copy-lock.js; update with `npm run copy:update`.', ''];

  for (const file of walk(build, '.html')) {
    parts.push(`=== page: ${relative(build, file)}`, ...pageText(readFileSync(file, 'utf8')), '');
  }

  const strings = new Set();
  const keep = (s) => {
    const t = tidy(s);
    if (/\s/.test(t) && /[a-z]/i.test(t)) strings.add(t);
  };
  for (const file of walk(join(root, 'src'), '.svelte')) {
    for (const [, block] of readFileSync(file, 'utf8').matchAll(/<script[^>]*>([\s\S]*?)<\/script>/gi)) {
      for (const s of scriptStrings(block)) keep(s);
    }
    for (const s of markupText(readFileSync(file, 'utf8'))) keep(s);
  }
  parts.push('=== source strings (sorted)', ...[...strings].sort(), '');
  return parts.join('\n');
}

const current = snapshot();

if (mode === 'update') {
  writeFileSync(lockPath, current);
  console.log(`Wrote ${relative(root, lockPath)}. Commit it with your copy change.`);
} else if (mode === 'check') {
  if (!existsSync(lockPath)) {
    console.error('copy.lock.txt is missing. Run `npm run copy:update`.');
    process.exit(1);
  }
  if (readFileSync(lockPath, 'utf8') === current) {
    console.log('Copy unchanged.');
  } else {
    const tmp = join(mkdtempSync(join(tmpdir(), 'copy-lock-')), 'copy.current.txt');
    writeFileSync(tmp, current);
    spawnSync('diff', ['-u', '--label', 'copy.lock.txt', '--label', 'built site', lockPath, tmp], { stdio: 'inherit' });
    console.error(
      '\nThe site copy differs from copy.lock.txt.\n' +
        '  If you meant to change the wording: npm run copy:update, and commit the lock file with it.\n' +
        '  If this was a refactor: the refactor changed copy. Restore the text above.'
    );
    process.exit(1);
  }
} else {
  console.error('Usage: node scripts/copy-lock.js check|update');
  process.exit(2);
}
